### ISSUE TITLE
rtl8723be on Fedora 23

### ISSUE THREAD

**Issue by feliperami94** [lwfinger/rtlwifi_new#106]
Hi, first of all, i'm new in Linux so please be patient. I have followed the instructions carefuly, but when i execute:
`sudo modprobe rtl8723be`
all i get is:
`modprobe: ERROR: could not insert 'rtl8723be': Required key not available`

I'm running Fedora 23 - kernel 4.4.6
Thank you!

**Comment by lwfinger** [comment]
I think that your BIOS has secure boot enabled. If you disable that feature, you should be able to load an unsigned module.

**Comment by feliperami94** [comment]
Is there a way to sign the module so i don't have to disable the secure boot? i don't know a lot about PCs and what i have read about disabling that feature is that it's too risky. The thing is, i already deleted the driver of my wifi card, so, i don't have even the poor signal i had in the past. Also, as i am new to Linux, i wanted to know if this type of support (for my wifi device) could be improved in new versions of Fedora. lwfinger, thank you very much for your help and patience, greetings from Colombia

**Comment by lwfinger** [comment]
There are a large number of articles available on signing modules. You would need to understand how to do it for Fedora.

Yes, disabling secure boot is a risk, particularly if you are running Windows, but very little risk if you are running Linux. When I received my current laptop, the first thing I did was delete Windows, and turn off secure boot. I have had no difficulties.

You have at least 4 options:

1. Wait for kernel 4.7 which will have the ant_sel logic.
2. Obtain the Fedora source, replace all the rtlwifi code with this repo, and build a signed module.
3. Build a Fedora kernel with signing turned off so that modules from this repo will load.
4. Disable secure boot in your BIOS.

Your choice.

**Comment by liningRS** [comment]
Thanks,I have solution my problem.


________________________________
发件人: lwfinger <notifications@github.com>
发送时间: 2016年3月28日 15:07
收件人: lwfinger/rtlwifi_new
主题: Re: [rtlwifi_new] rtl8723be on Fedora 23 (#106)


There are a large number of articles available on signing modules. You would need to understand how to do it for Fedora.

Yes, disabling secure boot is a risk, particularly if you are running Windows, but very little risk if you are running Linux. When I received my current laptop, the first thing I did was delete Windows, and turn off secure boot. I have had no difficulties.

You have at least 4 options:

  1.  Wait for kernel 4.7 which will have the ant_sel logic.
  2.  Obtain the Fedora source, replace all the rtlwifi code with this repo, and build a signed module.
  3.  Build a Fedora kernel with signing turned off so that modules from this repo will load.
  4.  Disable secure boot in your BIOS.

Your choice.

―

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
