### ISSUE TITLE
rtl8821ae single antenna

### ISSUE THREAD

**Issue by jasperry71** [lwfinger/rtlwifi_new#213]
I'm working with an rtl8821ae based dual band wifi module.  It appears that the antenna connection marked "M" is for 2.4GHz and the connection marked "A" is for 5GHz.  I would like to use a single dual band antenna instead of two.  Is there a way to configure the driver to use a single antenna for both 2.4GHz and 5GHz operation?

**Comment by lwfinger** [comment]
In a quick look at the code, I do not see where the antenna is being selected for either band.

In my tests, I did not get much difference in my 5G signal strengths. With a single antenna connected to A, the strength was -32 dBm. Moving that antenna to M gave -39 dBm. For 2.4 GHz, the strength went from -54 to -20 dBm.

**Comment by jasperry71** [comment]
In my testing, with antenna connected to M, 5G is -73 dBm and 2.4G is -36
dBm.  With antenna connected to A, 5G is -52 dBm and 2.4G is -68 dBm.
Are your tests with rtl8821ae? What brand module are you using?

Do you know of a way to swap the antenna selection?

**Comment by lwfinger** [comment]
My device came directly from Realtek. The difference between your results and mine are likely due to my NIC being connected via an ExpressCard adapter. It is located outside the computer which gives a path for the 5G signals.

I have written to my contact at Realtek to see if the radios are hard wired to the antenna connectors.

**Comment by jasperry71** [comment]
Hello Larry,

Just wondering if you have heard anything from your Realtek contact
regarding this issue.

Thanks,
Jonathan
