### ISSUE TITLE
RTL8723BE hard-blocked after suspend

### ISSUE THREAD

**Issue by FadedCoder** [lwfinger/rtlwifi_new#248]
I am having this problem for a long time, from when I was on Debian to now on Arch Linux. On Windows, I don't have this problem. Basically, issue #124.

I have an HP Pavilion 15-ab032tx with RTL8723BE driver. After I suspend and start, here are the infos -

uname -r:
`4.11.5-1-ARCH`

rfkill list:
```
1: phy0: Wireless LAN
	Soft blocked: no
	Hard blocked: yes
```

lspci | grep RTL
```
08:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8723BE PCIe Wireless Network Adapter
09:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8101/2/6E PCI Express Fast/Gigabit Ethernet controller (rev 0a)
```

cat /etc/modprobe.d/rtl8723be.conf:
```
options rtl8723be fwlps=Y ips=Y swlps=Y swenc=Y disable_watchdog=0 ant_sel=2
# Previously it was (I still have problem with this)
# options rtl8723be fwlps=N ips=N swlps=N swenc=Y disable_watchdog=1 ant_sel=2
```

I have also attached [dmesg](https://github.com/lwfinger/rtlwifi_new/files/1091306/log.txt)
 after starting on, suspending and waking up. If anything else is needed, please comment.

**Comment by lwfinger** [comment]
The "hard" blocked condition is due to the airplane mode switch being set. When that happens, the driver can only obey. I assume that your laptop only has a soft switch, probably a function key. That is likely controlled by a wmi driver. Does operating that key help? Unfortunately, there is little that I can do to help you find the bug.

BTW, your set of options is overly restrictive. The bug that was in power save was fixed a long time ago. In addition, the firmware is perfectly capable of handling encryption. It seems to me that ant_sel is the only option you need.

**Comment by FadedCoder** [comment]
Alright. I still am not able to fix the issue though. wmi buttons didn't help. I don't think this issue can be resolved without changing the network card.
