### ISSUE TITLE
usage explaination

### ISSUE THREAD

**Issue by thedanielhanke** [lwfinger/rtlwifi_new#25]
Hi,

beeing new to linux i wonder how exactly to use these drivers.

after installing kernel-headers i would guess i have to make && make install && modprobe xyz, but i am not sure if thats it?

Thanks in advance. Cheers

**Comment by troy-tan** [comment]
How to use this driver packet:
    1.sudo make install
    2.reboot

'sudo make install' will perform 'make' firstly and perform 'install' in Makefile.
In the Makefile of rtlwifi, when you do this action, it builds kernel modules for you 
and use depmod to build dependency of modules, this will update a file called modules.dep.
When you reboot, kernel will firstly recognize that there is a PCIE device and find modules in
modules.dep and decide which module to load. Finally, it has found modules call mac80211.ko, cfg80211.ko rtlwifi.ko and so on. Then, wifi in kernel starts to be inserted to kernel.This process
is similar to modprobe as you have mentioned.

The modprobe operation just makes wifi working temporary, because it does not update modules.dep.

If there is something wrong please correct me.

**Comment by thedanielhanke** [comment]
thanks a lot @troy-tan, thanks a lot!

**Comment by lwfinger** [comment]
I would add one additional caveat. It is never a good idea to buld anything as root. It may be difficult to write the Makefile, and some error might do harm to the system. In fact, at one time the kernel build would delete /dev/null if run as root. As you might expect, that caused all kinds of system failures. Thus you should do "make" as a regular user, then do "sudo make install". That way only the essential part is done as root, and there will not be any unintended side effects. For rtlwifi_new, those side effects are some files that the user cannot delete. That is not so bad, but it could get worse.

**Comment by dc740** [comment]
I did that, I can easily switch between this driver and this one: https://github.com/pvaret/rtl8192cu-fixes

I modprobe the modules I need depending on the implementation I want to try. But I don't see any interface with yours:
[  912.543563] Loading firmware rtlwifi/rtl8192cufw_TMSC.bin
[  912.543708] usbcore: registered new interface driver rtl8192cu

That's what I get when I load your drivers (after removing the other drivers modules with modprobe). And yet they don't work. 

My wifi works just fine when I load rtl8192cu-fixes.

So, questions:
1) Is there any extra step I'm missing?
2) What's the difference between these drivers and the FreedomBen drivers? are you guys working together?  (which I haven't tried yet).

**Comment by lwfinger** [comment]
1. None that I see.

2. I do not know what the differences are. We are not working together.

**Comment by DFOXpro** [comment]
btw is necessary to blacklist some default modules or some specific parameter for each device

**Comment by lwfinger** [comment]
If you have a kernel containing drivers r8821ae or r8723be from the staging tree, and you wish to use rtl8821ae or rtl8723be from this repo, then you will need to blacklist the staging version. There is a problem if you do not install these modules, but that is not a likely situation. If your kernel is updated, you will need to reinstall these modules. Once you get kernel 3.18.4 or newer, you can use those in the kernel as they are the same as found here.

The default parameters should be appropriate for all drivers. Some people claim to need to use certain parameters, but I am not convinced. In any case, "modinfo xxxx", where xxxx is the driver name, will show you what options are available.

**Comment by thedanielhanke** [comment]
Thank you all. Guess i can close this issue.
