### ISSUE TITLE
rtl8821ae wlan does not work correctly on openSUSE 42.2 LEAP

### ISSUE THREAD

**Issue by amaxi** [lwfinger/rtlwifi_new#250]
Hello,

I have a Lenovo ideapad 700 15ISK with RTL8821AE (WLAN+Bluetooth) PCIe card.

Env: openSUSE 42.2 (LEAP) + latest patch
Kernel: Linux linux-dalt 4.4.74-18.20-default #1 SMP Fri Jun 30 19:01:19 UTC 2017 (b5079b8) x86_64 x86_64 x86_64 GNU/Linux
Router: TP-Link wdr4300 with openWRT (LEDE 17.x)

hwinfo ->
54: None 00.0: 1070a WLAN
  [Created at net.126]
  Unique ID: AYEt.QXn1l67RSa1
  Parent ID: y9sn.2nCc7HMjyY7
  SysFS ID: /class/net/wlan0
  SysFS Device Link: /devices/pci0000:00/0000:00:1c.0/0000:02:00.0
  Hardware Class: network interface
  Model: "WLAN network interface"
  Driver: "rtl8821ae"
  Driver Modules: "rtl8821ae"
  Device File: wlan0
  HW Address: c8:3d:d4:79:50:7d
  Permanent HW Address: c8:3d:d4:79:50:7d
  Link detected: no
  Config Status: cfg=no, avail=yes, need=no, active=unknown
  Attached to: #29 (WLAN controller)
  
journalctl -k
Jul 08 21:50:50 linux-dalt kernel: rtl8821ae:rtl8821ae_download_fw():<0-0> Firmware is not ready to run!
Jul 08 21:50:53 linux-dalt kernel: wlan0: authenticate with 64:66:b3:47:5c:0b
Jul 08 21:50:53 linux-dalt kernel: rtl8821ae:rtl8821ae_download_fw():<0-1> Firmware is not ready to run!
Jul 08 21:50:53 linux-dalt kernel: wlan0: send auth to 64:66:b3:47:5c:0b (try 1/3)
Jul 08 21:50:53 linux-dalt kernel: wlan0: authenticated
Jul 08 21:50:53 linux-dalt kernel: rtl8821ae 0000:02:00.0 wlan0: disabling HT/VHT due to WEP/TKIP use
Jul 08 21:50:53 linux-dalt kernel: wlan0: associate with 64:66:b3:47:5c:0b (try 1/3)
Jul 08 21:50:53 linux-dalt kernel: wlan0: RX AssocResp from 64:66:b3:47:5c:0b (capab=0x431 status=0 aid=1)
Jul 08 21:50:53 linux-dalt kernel: wlan0: associated
Jul 08 21:50:53 linux-dalt kernel: cfg80211: Regulatory domain changed to country: HU
Jul 08 21:50:53 linux-dalt kernel: cfg80211:  DFS Master region: ETSI
Jul 08 21:50:53 linux-dalt kernel: cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp), (dfs_cac_time)
Jul 08 21:50:53 linux-dalt kernel: cfg80211:   (2402000 KHz - 2482000 KHz @ 40000 KHz), (N/A, 2000 mBm), (N/A)
Jul 08 21:50:53 linux-dalt kernel: cfg80211:   (5170000 KHz - 5250000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 2000 mBm), (N/A)
Jul 08 21:50:53 linux-dalt kernel: cfg80211:   (5250000 KHz - 5330000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 2000 mBm), (0 s)
Jul 08 21:50:53 linux-dalt kernel: cfg80211:   (5490000 KHz - 5710000 KHz @ 160000 KHz), (N/A, 2700 mBm), (0 s)
Jul 08 21:50:53 linux-dalt kernel: cfg80211:   (57000000 KHz - 66000000 KHz @ 2160000 KHz), (N/A, 4000 mBm), (N/A)

  
Problem:
When I am connecting to the Wifi router by using WLAN (5 GHz or 2.4 GHz) then the connection is not stable and the speed is really slow aprx: 5-10k/s to the Internet and 190-250kb/s in the local network.
I tested it on other devices but I didn't experience this issue with them expect in Lenovo 700 (with RTL8821AE)

So the main problem is that the connection is not stable between my laptop and Internet (and local network), it means that one web page can be loaded but other pages can not fetch. 
Temporary solution: When I re-connect to the Wifi then it works again for some seconds, but after something happens and no more pages could be fetch.

Could you please give me any help, or idea what causes the problem?

Thanks!

**Comment by moriel5** [comment]
I have the same problem, but on the IdeaPad 300-15ISK.
Actually, this network card is what caused me to speed up my plan of moving over to Linux, as I could almost never connect to (or find) my home network, and even then, I kept having disconnection issues (it got to the point that I had left my laptop completely off for about half a year).

Solus, Kernel 4.12.3-5 x86-64, Lenovo IdeaPad 300-15.

**Comment by amaxi** [comment]
Not so good news.
I don't think that RTL8821AE device (hardware) is wrong but I assume this causes the bug in the driver.
I hope the issue will be solved in the near future. 
Hope dies last :-)

**Comment by moriel5** [comment]
Update: After installing the latest preview drivers from here, 2.4Ghz works without a single issue(I had tested it for a few hours straight from work) even when waking from sleep.

I shall test 5Ghz at home, since my work network runs on an old adsl2+ 2.4Ghz only b/g D-Link Router (good thing my Xiaomi Mi 3 Router, which I had flashed on it Padavan, also supports ac).

**Comment by amaxi** [comment]
Cool, it is good new.
I am really waiting for the next openSUSE release (LEAP 42.3 that will be released in 17 hours)
After I upgraded to the new release I will test it.
If it doesn't work then I will upgrade to Tumbleweed that use the latest kernel but I think SUSE developer team will port it to latest LEAP, I hope so.

I am waiting for your feedback about 5GHz tests. Thanks.

**Comment by moriel5** [comment]
The 5Ghz should arrive in about 8-10 hours, since I'll need to sleep (I am running the tests instead of sleeping), and I won't have time to log in until the end of the morning.

For the time being though, I have YouTube streaming speed results for both 2.4Ghz and 5Ghz (I can say that streaming a ~9 minute LinusTechTips clip streamed without any interferences, that's definitely something good about the current situation with the RTL8821AE).

2.4Ghz:
Minimum speed: ~7800 Kilobits per second;
Average speed: ~17500 Kilobits per second;
Maximum speed: ~22400 Kilobits per second;

5Ghz:
Minimum speed: ~4500 Kilobits per second;
Average speed ~7000 Kilobits per second;
Maximum speed ~9800 Kilobits per second;

This is on an effective plan of ~34 Megabits per second (We are paying for 40, our area provides up to ~38, and our modem+router (TD-W9970) is not necessarily efficient, providing ~28-34Mbps, whereas our old one (VEGN2100, provided by the ISP, extremely unstable though, disconnecting very often, and settings getting corrupted multiple times (I saw these happening everywhere I had seen this product, and representatives of multiple ISP's recommend not to even think about it ) managed ~34-38Mbts (I have verified it's efficiency).

Wired testing shall commence (As mentioned, we use a Xiaomi Mi 3 Router, running Padavan, for wireless, so I shall connect my laptop to it as well (modem efficiency of the TD-W9970 was determined vua a wired connectoon, without the Mi 3 Router in between).

**Comment by amaxi** [comment]
Firstly, I would like to thank you for your night test.

The wifi issue is not solved after the has been upgraded to LEAP 42.3
Next I will upgrade it to Tumbleweed, but the current kernel version is just 4.11.8 in it,
I am waiting for the next kernel release in the Tumbleweed that maybe contains that commit
a24cb56. 

How did you test it? Did you compile custom kernel (including the latest commits (a24cb56)) for the test?

Thanks

**Comment by moriel5** [comment]
Sorry for the lateness (I had forgotten about most of the world today, installing Ubuntu Budgie 17.10 on my desktop, on the 4th hard drive (WD 80GB SATA2, and pulled from an old PC that was going to be recycled).

5Ghz has not died on me either, despite the weaker reception.
I had not had the time to check the YouTube streaming speed on wired, though.

I am running the kernel provided to me by the distro (it did not have any special fixes for the RTL8821AE), at version 4.12.3-5.

My situation had only changed after compiling and installing the drivers here, so it is probably not due to the kernel.

**Comment by moriel5** [comment]
It is rather weird that my post had not gotten through to GitHub , however on wired, it was at ~22990-30000Kbps until stabilizing (which took about 12-15 seconds), upon which it had stayed at 30013Kbps.

**Comment by amaxi** [comment]
So, I upgraded from openSUSE LEAP 42.3 to Tumbleweed-Snapshot20170725.
I compiled the modules with kernel-4.11.8 and
copy 4 files from git/rtlwifi_new-master/ to /lib/modules/4.11.8-2-default/kernel/drivers/net/wireless/realtek/rtlwifi/
rtl_pci.ko -> /lib/modules/4.11.8-2-default/kernel/drivers/net/wireless/realtek/
rtlwifi.ko -> /lib/modules/4.11.8-2-default/kernel/drivers/net/wireless/realtek/
btcoexist.ko -> /lib/modules/4.11.8-2-default/kernel/drivers/net/wireless/realtek/btcoexist/
rtl8821ae.ko -> /lib/modules/4.11.8-2-default/kernel/drivers/net/wireless/realtek/rtlwifi/rtl8821ae/

Results: it seems to work perfectly with kernel-4.11.8. 
A have tested it, downloaded and streamed from Youtube, Mixcloud and randomly browsed pages in 10 tab in 2 hours.
I have a 20/20Mbps Internet connection. I downloaded some ISO from Internet via Wifi and Cabel too and the download speed is same (2,4MiB/s) in both cases. 

Summary: The patch (commit a24cb56) is solved the stability and speed issues. All in all the usage is much more efficiently works then before.

Test with kernel 4.12.x later:
At this point I have to wait for the next stable kernel to arrive into SUSE Tumbleweed (kernel-4.12.x or higher).
I think it will come aprx. 1-2 weeks later.

**Comment by moriel5** [comment]
That's great news!
Hopefully the drivers will be merged into the mainline kernel before 4.13 comes out.

**Comment by amaxi** [comment]
I reported the issue and the solution for the community in the openSUSE forum.
https://forums.opensuse.org/showthread.php/526207-RTL8821AE-PCIe-Wireless-Network-Adapter-does-not-work-correctly-on-LEAP-42-2-and-42-3
I hope they will find this useful and help the others.

Thanks for your help

**Comment by lwfinger** [comment]
When openSUSE decided to keep kernel 4.4 for Leap 42.3, they cut themselves off from nearly ALL of the recent driver development work. Unless some openSUSE kernel developer is willing to put in the effort, then only the fixes for kernel crashes will be back ported. Fixes for the dropping of the wifi connection have a much lower priority.

For you, you can either install out of kernel drivers from this repo, OR you can enable the Kernel_head_standard repo, and run the modern kernels from there.

**Comment by amaxi** [comment]
Thanks for the information. 

> Fixes for the dropping of the wifi connection have a much lower priority.
>
Good to know this information. Thanks for sharing it with us.

One Maintainer (Akoellh) has created new package with your fixes
https://software.opensuse.org/package/rtlwifi_new

I would like to thank you for your efforts to solve this issues. The fix works perfectly since I am using it and I don't have stability and speed problem anymore.
