### ISSUE TITLE
rtl8821ae

### ISSUE THREAD

**Issue by HanaO00** [lwfinger/rtlwifi_new#264]
Hello, i have disconnections with the rtl8821ae, on kernel 4.12, how can i fix that ?

Thank you

**Comment by pgueckel** [comment]
Please tell me! I have been trying since at least the start of 2017 or earlier :-(((

**Comment by pcP1r4t3** [comment]
Try this: https://gauravssnl.wordpress.com/2017/06/18/how-to-fix-realtek-rtl8723be-wireless-network-adapter-low-wi-fi-signal-issue-on-ubuntulinux-os/
It worked for me.
Hope it works for you :)

**Comment by pgueckel** [comment]
I haven't tried that yet. I was under the understanding that rtlwifi_new is in the 4.12 kernel, so it should not be necessary to compile and install the update. I am running kernel-4.12.8-300.fc26.x86_64 on Fedora 26. Also, I do not believe that rtl8821ae has 2 antennas. When I run modinfo, there is no ant_sel option listed. I could try it, just in case there are unreported options.

**Comment by lwfinger** [comment]
The code in rtlwifi_new is older than 4.12 due to a problem with the ant_sel code for RTL8723BE in 4.12 and later does not work.

No one has yet reported a single-antenna problem for the RTL8821AE, thus there is no code to support it. IF you look at your device, find you have only a single antenna, AND get better signals when that one antenna is switched to the other connector, THEN we might consider adding the ant_sel option to rtl8821ae. Until all the conditions above are met, then there will be no code changes.

**Comment by christianmtr** [comment]
I just comment in [other issue](https://github.com/lwfinger/rtlwifi_new/issues/261#issuecomment-338260135) about it, maybe can help you.
