### ISSUE TITLE
RTL8821ae disconnecting from WiFi

### ISSUE THREAD

**Issue by zwrg** [lwfinger/rtlwifi_new#296]
After few minutes of stability DC, after `sudo sudo modprobe -r rtl8821ae && sudo modprobe rtl8821ae` and few minutes.. DC. Help me with this problem because no one can help me, every tutorials askubuntu etc. didnt help either. I don't know where exactly is the problem: Ubuntu 17.10, 4.13.0-17-generic.

**Comment by stonewareslord** [comment]
Are there any errors in dmesg?

**Comment by pachecohjr** [comment]
I am going through the same exact occurrence. The first to me being the most concerning.

...
[    0.000000] [Firmware Bug]: TSC_DEADLINE disabled due to Errata; please update microcode to version: 0x25 (or later)
[    0.076536] Error parsing PCC subspaces from PCCT
[    0.755603] (NULL device *): hwmon_device_register() is deprecated. Please convert the driver to use hwmon_device_register_with_info().
[   11.354422] tpm_crb MSFT0101:00: can't request region for resource [mem 0xa4fff000-0xa4fff02f]
[   70.720492] Could not find key with description: [013ab09180c8ac2a]
[   70.720497] Could not find valid key in user session keyring for sig specified in mount option: [013ab09180c8ac2a]
[   96.293394] rtlwifi: AP off, try to reconnect now
[  106.365183] rtlwifi: AP off, try to reconnect now
[  223.243599] [drm:intel_pipe_update_end [i915]] *ERROR* Atomic update failure on pipe A (start=13574 end=13575) time 351 us, min 1073, max 1079, scanline start 1072, end 1096
[  254.832719] [drm:intel_pipe_update_end [i915]] *ERROR* Atomic update failure on pipe A (start=15471 end=15472) time 348 us, min 1073, max 1079, scanline start 1070, end 1071
[  279.955336] rtlwifi: AP off, try to reconnect now
[  290.037902] rtlwifi: AP off, try to reconnect now
...
[  367.589336] wlp3s0: associated
[  367.589344] IPv6: ADDRCONF(NETDEV_CHANGE): wlp3s0: link becomes ready
[  588.349922] proc_thermal 0000:00:04.0: Unsupported event [0x84]
[  702.338487] r8169 0000:02:00.0 enp2s0: link up
[  702.338502] IPv6: ADDRCONF(NETDEV_CHANGE): enp2s0: link becomes ready
[  756.994640] NETDEV WATCHDOG: enp2s0 (r8169): transmit queue 0 timed out
[  756.994652] ------------[ cut here ]------------

...
[ 1474.898344] IPv6: ADDRCONF(NETDEV_UP): wlp3s0: link is not ready
[ 1475.114857] IPv6: ADDRCONF(NETDEV_UP): wlp3s0: link is not ready
[ 1475.185357] IPv6: ADDRCONF(NETDEV_UP): wlp3s0: link is not ready
[ 1481.387530] wlp3s0: authenticate with 00:25:9c:23:84:41
[ 1481.391038] wlp3s0: send auth to 00:25:9c:23:84:41 (try 1/3)
[ 1481.413280] wlp3s0: authenticated
[ 1481.413410] rtl8821ae 0000:03:00.0 wlp3s0: disabling HT as WMM/QoS is not supported by the AP
[ 1481.413412] rtl8821ae 0000:03:00.0 wlp3s0: disabling VHT as WMM/QoS is not supported by the AP
[ 1481.416967] wlp3s0: associate with 00:25:9c:23:84:41 (try 1/3)
[ 1481.421154] wlp3s0: RX AssocResp from 00:25:9c:23:84:41 (capab=0x411 status=0 aid=6)
[ 1481.531857] wlp3s0: associated
[ 1481.531867] IPv6: ADDRCONF(NETDEV_CHANGE): wlp3s0: link becomes ready
[ 1751.313296] rtlwifi: AP off, try to reconnect now
[ 1751.313326] wlp3s0: Connection to AP 00:25:9c:23:84:41 lost
[ 1761.393551] rtlwifi: AP off, try to reconnect now
[ 1768.212582] wlp3s0: Connection to AP 00:00:00:00:00:00 lost
[ 1783.101597] IPv6: ADDRCONF(NETDEV_UP): wlp3s0: link is not ready
[dmesg_20171208.txt](https://github.com/lwfinger/rtlwifi_new/files/1541745/dmesg_20171208.txt)

**Comment by pachecohjr** [comment]
I found this solution for one of the errors I'm going through but I am kinda lost where to start. I have an Intel Core processor.

https://bbs.archlinux.org/viewtopic.php?id=230204

**Comment by riper384** [comment]
only these lines about connection:

[  +0,272859] rtl8821ae: Using firmware rtlwifi/rtl8821aefw_29.bin
[  +0,000008] rtl8821ae: Using firmware rtlwifi/rtl8821aefw_wowlan.bin
[  +0,035183] ieee80211 phy0: Selected rate control algorithm 'rtl_rc'
[  +0,000609] rtlwifi: rtlwifi: wireless switch is on

[  +0,014760] rtl8821ae 0000:01:00.0 wlp1s0: renamed from wlan0

[  +0,782392] IPv6: ADDRCONF(NETDEV_UP): wlp1s0: link is not ready
[  +0,330372] IPv6: ADDRCONF(NETDEV_UP): wlp1s0: link is not ready
[  +0,133689] IPv6: ADDRCONF(NETDEV_UP): wlp1s0: link is not ready
[  +6,763704] wlp1s0: authenticate with b4:ee:b4:92:1f:d7
[  +0,005940] wlp1s0: send auth to b4:ee:b4:92:1f:d7 (try 1/3)
[  +0,002993] wlp1s0: authenticated
[  +0,007717] wlp1s0: associate with b4:ee:b4:92:1f:d7 (try 1/3)
[  +0,008080] wlp1s0: RX AssocResp from b4:ee:b4:92:1f:d7 (capab=0x1411 status=0 aid=1)
[  +0,002370] wlp1s0: associated
[  +0,000020] IPv6: ADDRCONF(NETDEV_CHANGE): wlp1s0: link becomes ready
[  +0,074205] wlp1s0: Limiting TX power to 20 (20 - 0) dBm as advertised by b4:ee:b4:92:1f:d7

and after changing modprobe and during this process

[  +3,044465] random: crng init done
[gru 8 11:52] wlp1s0: deauthenticating from b4:ee:b4:92:1f:d7 by local choice (Reason: 3=DEAUTH_LEAV
[gru 8 11:53] rtlwifi: AP off, try to reconnect now
[  +7,245810] wlp1s0: Connection to AP 00:00:00:00:00:00 lost
[  +0,367206] rtl8821ae: Using firmware rtlwifi/rtl8821aefw_29.bin
[  +0,000016] rtl8821ae: Using firmware rtlwifi/rtl8821aefw_wowlan.bin
[  +0,002396] ieee80211 phy0: Selected rate control algorithm 'rtl_rc'
[  +0,004357] rtlwifi: rtlwifi: wireless switch is on
[  +0,001808] rtl8821ae 0000:01:00.0 wlp1s0: renamed from wlan0
[  +0,040976] IPv6: ADDRCONF(NETDEV_UP): wlp1s0: link is not ready
[  +0,194834] IPv6: ADDRCONF(NETDEV_UP): wlp1s0: link is not ready
[  +0,068147] IPv6: ADDRCONF(NETDEV_UP): wlp1s0: link is not ready
[  +6,498340] wlp1s0: authenticate with b4:ee:b4:92:1f:d7
[  +0,035221] wlp1s0: send auth to b4:ee:b4:92:1f:d7 (try 1/3)
[  +0,104487] wlp1s0: send auth to b4:ee:b4:92:1f:d7 (try 2/3)
[  +0,002952] wlp1s0: authenticated
[  +0,001254] wlp1s0: associate with b4:ee:b4:92:1f:d7 (try 1/3)
[  +0,003605] wlp1s0: RX AssocResp from b4:ee:b4:92:1f:d7 (capab=0x1411 status=0 aid=1)
[  +0,166247] wlp1s0: associated
[  +0,000026] IPv6: ADDRCONF(NETDEV_CHANGE): wlp1s0: link becomes ready
[  +0,003926] wlp1s0: Limiting TX power to 20 (20 - 0) dBm as advertised by b4:ee:b4:92:1f:d7
[gru 8 11:55] perf: interrupt took too long (2542 > 2500), lowering kernel.perf_event_max_sample_rat

[gru 8 11:52] wlp1s0: deauthenticating from b4:ee:b4:92:1f:d7 by local choice (Reason: 3=DEAUTH_LEAVING)
[gru 8 11:53] rtlwifi: AP off, try to reconnect now
[  +7,245810] wlp1s0: Connection to AP 00:00:00:00:00:00 lost
[  +0,367206] rtl8821ae: Using firmware rtlwifi/rtl8821aefw_29.bin
[  +0,000016] rtl8821ae: Using firmware rtlwifi/rtl8821aefw_wowlan.bin
[  +0,002396] ieee80211 phy0: Selected rate control algorithm 'rtl_rc'
[  +0,004357] rtlwifi: rtlwifi: wireless switch is on
[  +0,001808] rtl8821ae 0000:01:00.0 wlp1s0: renamed from wlan0
[  +0,040976] IPv6: ADDRCONF(NETDEV_UP): wlp1s0: link is not ready
[  +0,194834] IPv6: ADDRCONF(NETDEV_UP): wlp1s0: link is not ready
[  +0,068147] IPv6: ADDRCONF(NETDEV_UP): wlp1s0: link is not ready
[  +6,498340] wlp1s0: authenticate with b4:ee:b4:92:1f:d7
[  +0,035221] wlp1s0: send auth to b4:ee:b4:92:1f:d7 (try 1/3)
[  +0,104487] wlp1s0: send auth to b4:ee:b4:92:1f:d7 (try 2/3)
[  +0,002952] wlp1s0: authenticated
[  +0,001254] wlp1s0: associate with b4:ee:b4:92:1f:d7 (try 1/3)
[  +0,003605] wlp1s0: RX AssocResp from b4:ee:b4:92:1f:d7 (capab=0x1411 status=0 aid=1)
[  +0,166247] wlp1s0: associated
[  +0,000026] IPv6: ADDRCONF(NETDEV_CHANGE): wlp1s0: link becomes ready
[  +0,003926] wlp1s0: Limiting TX power to 20 (20 - 0) dBm as advertised by b4:ee:b4:92:1f:d7
[gru 8 11:55] perf: interrupt took too long (2542 > 2500), lowering kernel.perf_event_max_sample_rate to 78500

**Comment by pachecohjr** [comment]
I just went ahead and refollowed with the instructions on 
https://askubuntu.com/questions/972335/ubuntu-17-10-wifi-issues
and reinstalled the driver. 

You have some options after reinstalling the driver seen on here, if the first solution doesn't work:
https://askubuntu.com/questions/797213/wireless-disconnect-issues-ubuntu-16-04-with-rtl8821ae

I was given a warning about messing with the firmware's power save control on a previous issue thread here by lwfinger. I asked for help on Ubuntu chat and was notified that an Ubuntu 17.10 update (specifically package linux-image-extra-4.13.0-19-generic) provides a module file for rtl8821ae and is more up to date than the firmware driver here updated a year ago. I am not saying don't try the firmware driver in this repository first if you haven't already.

**Comment by lwfinger** [comment]
This posting has misinfo just like most of the postings here. That is the main reason I ignore most postings!!

First of all, I did not warn against messing with the power-save options. I merely pointed out that the bug that forced usage of those options was fixed a long time ago. If you want to throw any or all those options at the driver, go ahead, but remember that they are not needed!

Secondly, the PATH of a firmware file is well known in advance as it is coded into the driver, which is why modinfo knows about it. If you are going to discuss which firmware works, and which fails, then you MUST post the md5sum for those files. That is the only way to determine what file you are using.

Thirdly, I have no idea what is happening with your devices, but mine running a kernel 4.13 or later is rock solid. If you are running such a kernel and the in-kernel driver is failing, then you need to suspect the user-space code of your distro. For the record, I use NetworkManager with openSUSE Tumbleweed or Leap 42.3.

**Comment by pachecohjr** [comment]
I don't like to promote misinformation so I'll do you the favor and delete the post. I really thank you for your contribution on github, and because of that, I will not write what I want to write.

Just go ahead and ignore.
