### ISSUE TITLE
rtl8192cu | Fedora 27 | Kernel 4.14.14-300.fc27.x86_64 | Unknown symbol rtl_dbgp_flag_init (err 0)

### ISSUE THREAD

**Issue by Pant** [lwfinger/rtlwifi_new#314]
I have an Edimax EW-7811Un, with rtl8192cu. I use Fedora 27 64bit and kernel 4.14.14-300.fc27.x86_64.
Problem is when I run `modprobe rtl8192cu` I get:
> modprobe: ERROR: could not insert 'rtl8192cu': Unknown symbol in module, or unknown parameter (see dmesg)

`dmesg`:
> [11960.656012] usbcore: deregistering interface driver rtl8192cu
> [11964.830335] rtl_usb: Unknown symbol rtl_dbgp_flag_init (err 0)

Also, `lsusb`:
> Bus 001 Device 002: ID 7392:7811 Edimax Technology Co., Ltd EW-7811Un 802.11n Wireless Adapter [Realtek RTL8188CUS]

I used to use the [pvaret/rtl8192cu-fixes/](https://github.com/pvaret/rtl8192cu-fixes/) repository and was working good with the normal kernel driver, but the developer said:
> The new rtl8xxxu driver initially introduced in kernel 4.4 works pretty well these days, and you almost certainly should prefer it to this repository.
...and stop supporting this repo. Though it doesn't work with the normal kernel driver ether.

**Comment by lwfinger** [comment]
With kernel 4.14, there is no need, or advantage, to using this repo for any of the rtlwifi drivers other than rtl8822be or rtl8723de.

You are getting the error because this repo assumes that CONFIG_RTLWIFI_DEBUG is set to "Y". Apparently, that is not true for F27. If you still wish to use this repo despite what I said above, then find the two lines in Makefile that reference CONFIG_RTLWIFI_DEBUG and remove them,

If you have an RTL8192CU device, you will need to blacklist either rtl8xxxu or rtl8192cu depending on which driver you wish to use you wish to use.

**Comment by Pant** [comment]
Thanks for your fast reply.
For the record, blacklisting rtl8192cu with the following, the wifi dongle worked.

`# nano /etc/modprobe.d/rtl8192cu.conf`:
```
install rtl8192cu /bin/false
```
