### ISSUE TITLE
Very low range RTL8723DE

### ISSUE THREAD

**Issue by vaider1** [lwfinger/rtlwifi_new#322]
Using arch, kernel version 4.15 on HP Pavilion 14, i need to be within ~3 meters of the AP to be able to connect to it, and the signal drops frequently. With kernel 4.14 the range was much higher. there was also something like a month between installing it on 4.14 and than 4.15, might be some commit that might have made it worse in the meantime?

**Comment by lwfinger** [comment]
There have been no changes in the driver for RTL8723DE since it was placed into the extended branch. The only changes in the repo have been to fix the build process.

Whenever anyone has waek signals with any HP laptop, I immediately wonder if this is another case of HP being cheap and only installing a single antenna, and then failing to encode the EFUSE correctly for the choice of connector. This problem is the reason that the ant_sel parameter was added to the rtl8723be driver, and I see that Realtek also added it to the 8723de driver.

Try loading the driver with choices of ant_sel other than 0, which is the default. If you want to quantify this choice, use the following command:

sudo iw dev wlan1 scan | egrep "SSID|signal"

Substitute the name of your device for the "wlan1" above. The signal of interest will be the one listed above the SSID of your AP.

Note: I do not have one of these devices, thus I can only do compile testing.

**Comment by vaider1** [comment]
thanks for the help, the HP case is indeed crappy, and using the option "ant_sel=2" fixed the problem!
