### ISSUE TITLE
Instructions for getting to work on ubuntu?

### ISSUE THREAD

**Issue by als5ev** [lwfinger/rtlwifi_new#328]
I completely realize that you aren't going to solve this problem for us but can you give some guidance for how to fix the problem ourselves? I'm assuming the installation instructions wont work to for ubuntu based on the preface in the README.

**Comment by lwfinger** [comment]
The easiest thing is to follow the steps in http://ubuntuhandbook.org/index.php/2017/02/ukuu-install-latest-kernels-ubuntu-linux-mint/, and then install the latest 4.15.X available. Run it and do not use this repo.

If you really want to use this repo, then a build error should be found inside a place where the kernel version is tested with a statement that looks like 
#if LINUX_VERSION_CODE < KERNEL_VERSION(4, 7, 0)
The problem will be that Ubuntu has backported a feature such that the test needs to be for a different kernel version. You will need to adjust the tested version number, which will need to be larger. Otherwise, I have no other suggestions.
