### ISSUE TITLE
RTL8821CE

### ISSUE THREAD

**Issue by rpascual0812** [lwfinger/rtlwifi_new#338]
Hi, my HP Probook 440 G4 says my driver code is rtl8821ce. Do you have a driver for this? Thanks.

**Comment by lwfinger** [comment]
I got a stand-alone version yesterday, but I have not yet had a chance to work with it. The raw tar file is in the extended branch. Good luck.

**Comment by Strit** [comment]
Uh, just got a Lenovo with this chip in it, so following this to see where it goes.
I got the wifi working, but not the bluetooth.

**Comment by lwfinger** [comment]
I have no BT drivers in any form.

**Comment by mirh** [comment]
Ubuntu folks supposedly got them. 
https://patchwork.ozlabs.org/patch/859094/

**Comment by rpascual0812** [comment]
I meant HP Probook 440 G5. I got mine working using the instructions from here [https://forums.linuxmint.com/viewtopic.php?t=260333](url)

**Comment by Strit** [comment]
@rpascual0812 
That's what I'm currently doing to get wifi working aswell. But I have to make and make install each time I have a kernel update.
Which is annoying.

**Comment by lwfinger** [comment]
Every new kernel requires an update to all external drivers. That cannot be helped. Linux used to allow older drivers to be loaded, but the users abused the situation, and kernel devs wasted a lot of time chasing apparent bugs that were just due to layout changes. That is the reason for the current rule.

Realtek is working hard to get the drivers into the kernel, but the rate of release of new chips is very high, and HP and Lenovo only care that the Windows drivers are ready.

**Comment by rpascual0812** [comment]
@Strit Well, we don't have a choice. I updated my kernel to 4.15.9 before I installed the driver to avoid having to install it all over again in a long while. Since this is a company laptop, it is duly noted not to buy any HP laptop for personal consumption in the future. My brother's ASUS with Realtek chip is working just fine.
