### ISSUE TITLE
lspci | grep Wireless shows nothing

### ISSUE THREAD

**Issue by SiyahaS** [lwfinger/rtlwifi_new#341]
So when I tried to use `lspci | grep` Wireless nothing shows up. I tried to use `lspci` itself and there is only these two lines that looks like related to network.

    02:00.0 Network controller: Realtek Semiconductor Co., Ltd. Device d723
    03:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 15)

I reached out to HP to ask which realtek wireless driver that I should use, and they said its a `realtek wlan rt tiffany bt bgn 1x1 (fx) 915618-002`. I tried to search it out aswell but could not come up with any rtlxxxxxx type name. By the way wireless is working on windows 10, so I know this is a driver related issue.

A detailed [lshw output](https://drive.google.com/open?id=1Jd3dA45gYjFgWdgXMOY-7V-dAuqD5nV9) and [lspci output](https://drive.google.com/open?id=1uPQZI53ZV43KG3KEQtmpl-RyexVN1Prc) in case someone help me with it.

Thanks in advance.

**Comment by lwfinger** [comment]
When you post lspci output, you should always use the "-nn" switch, i.e. "lspci -nn". That way, the PCI IDs will be listed. Those are important because that is the information that tells the kernel what driver to load.

In your case, I am guessing that you have an RTL8723DE device  as the ID for it is 10ec:d723. If that is correct, then you need the extended branch of this repo. Do the following commands AS A REGULAR USER:

git clone https://github.com/lwfinger/rtlwifi_new.git -b extended
cd rtlwifi_new
make
sudo make install
sudo reboot

Obviously, you will need git, make, and gcc installed for those commands to work. You will also need the kernel headers development package. As you cleverly failed to indicate what distro you are using, I cannot give you any hints. Each distro is different, but if you get and error that /lib/modules/..../build is not found, then you need the headers package.

A word of caution: Whenever your distro updates your kernel, you will need to repeat the make and sudo make install steps, otherwise, your wireless will fail again. It is also good practice to do a 'git pull' in order to get the latest updates.

**Comment by SiyahaS** [comment]
Thanks for help, I thought I already did the same steps, yet there seems to be one missing/wrong. But there is a problem. The wifi module is getting signals too low.(I'm right before the wireless modem). Its not like that in Windows, where it can detect at much longer range. And sorry about, I forgot to tell that I'm using Ubuntu 16.04.4 64 bit. Any suggestion that I should do about wifi signal strength? Is there a low power mode in wifi driver etc?

**Comment by lwfinger** [comment]
That is a problem caused by HP. Read about ant_sel for RTL8723BE. The DE has the same problem.

**Comment by edbergavera** [comment]
Hello,

In my case, I have HP Notebook - 14-bs577tu using RTL8723DE. I got it working using the guide here. Thanks @lwfinger. I agree that the signal strength is low but the important thing for me right now is wifi is working. I'll look into solving the signal strength if needed.

**Comment by lwfinger** [comment]
OK, but ant_sel=2 will likely fix the signal strength.
