### ISSUE TITLE
Is there support for RTL 8723de?

### ISSUE THREAD

**Issue by samarth1402** [lwfinger/rtlwifi_new#342]
If yes, how do i install it. I am not able to use internet on my ubuntu system.

**Comment by lwfinger** [comment]
Yes, there is support, but it is not yet in the kernel. Since you found this GitHub project, you probably have read some of the rtl8723de threads. You could download the zip form of the extended branch of this repo to get the source files, but without Internet service to get the optional packages needed to build out-of-kernel modules, you are not likely to get very far. If it is physically impossible for you to connect a wire, then I suggest that you buy or borrow a USB stick to get a wireless connection to aid the process. The only requirement is that the device be Linux compatible.

If you find a device within your budget and need help in determining if it will work with Linux, please post a link to the device or a make and model, and I will help.

**Comment by samarth1402** [comment]
Sir, I can get a lan cable for installing driver for my RTL card. 
I am sorry but I am new to all this. Is there a step by step guide for how to get the source files and how to install them. 
Also, is it stable or shall I wait for it to be added to kernel.

**Comment by lwfinger** [comment]
You need to have git, make, gcc, and the kernel-headers installed. As the method for installing packages differs by distro, you will need to investigate the exact method for yours. The instructions on how to obtain and build the driver have been posted many times, but they are simple and I will repeat them. To install the driver code and build the driver, do the following:

git clone https://github.com/lwfinger/rtlwifi_new.git -b extended
cd rtlwifi_new
make
sudo make install
sudo reboot

The driver is under development. If you want absolutely rock solid, then you need to wait for about two years. On the other hand, no one has complained of system crashes, so I think it is pretty good. As I do not own any examples of this device, I have no first-hand experience.
