### ISSUE TITLE
RTL8821AE Fails to Authenticate to 5GHz WPA2 Network [Arch Linux]

### ISSUE THREAD

**Issue by warrenpw** [lwfinger/rtlwifi_new#347]
Initially, I noticed after a kernel update to 4.15 that the kernel-provided rtl module was no longer letting me connect to my 5GHz WPA2-personal encrypted wireless network with authentication timing out. I assumed this was potentially due to a fix that had been committed upstream but not included in the kernel, so I downloaded the available source code for the extended branch, built, and installed it, but the authentication seems to still time out. I did verify the password was correct multiple times!

Note that, at this time, connections to 2.4GHz WPA2-personal encrypted networks still works fine.

$ uname -r: 4.15.15-1-ARCH

Dmesg output:
```[ 1082.318137] wlp6s0: authenticate with 38:d5:47:73:a2:bc
[ 1082.318944] wlp6s0: send auth to 38:d5:47:73:a2:bc (try 1/3)
[ 1082.421378] wlp6s0: send auth to 38:d5:47:73:a2:bc (try 2/3)
[ 1082.525405] wlp6s0: send auth to 38:d5:47:73:a2:bc (try 3/3)
[ 1082.629420] wlp6s0: authentication with 38:d5:47:73:a2:bc timed out
```
This repeats about 4 times before falling back to the 2.4GHz connection. I did also attempt to get more debugging information by setting the module debug_level option to 5, but no extra output seemed to be generated.

[modinfo.txt](https://github.com/lwfinger/rtlwifi_new/files/1901227/modinfo.txt)

Let me know if I can help by providing any additional information.

**Comment by lwfinger** [comment]
On my system, WPA2 in the 5GHz band works fine. I have connected to both channel 40 and 153.

Did you change anything other than the kernel? What kernel did you use previously? What channel is your 5G AP using? Please post the output of 

dmesg | egrep "rtl8821|wlp6s0"

**Comment by warrenpw** [comment]
My 5GHz network is currently using channel 157, which hasn't changed any time recently.

I also meant to clarify that I'm using the rtl8821ae module, but the hardware card is an RTL
8812AE:
```
$ lspci | grep Wireless
06:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8812AE 802.11ac PCIe Wireless Network Adapter (rev 01)
```
Only the kernel was changed before the issues started occurring.

Requested dmesg output attached; generated after startup, connecting to 2.4 ghz network, then attempting to connect to 5GHz network:
[dmesg_grep.txt](https://github.com/lwfinger/rtlwifi_new/files/1905483/dmesg_grep.txt)

**Comment by lwfinger** [comment]
I do not have an RTL8812AE, only an RTL8821AE. There could be differences.

What kernel did you use previously? Please answer all my questions!

Does ARCH provide kernel source in a git repo? Any chance of bisecting between 4.15.15-1 and the one that worked? I do not think there were any changes that would affect WPA2 encryption anytime through the 4.15.x sequence, but a bisection should tell us which commit failed.

**Comment by warrenpw** [comment]
Apologies, I should have looked at your response more closely.

The most recent update of the kernel was on April 11th from 4.15.9-1 to 4.15.15-1 according to pacman.log:
```
$ grep "upgraded linux" /var/log/pacman.log
{snip}
[2018-02-28 15:09] [ALPM] upgraded linux (4.14.3-1 -> 4.15.6-1)
[2018-03-16 19:54] [ALPM] upgraded linux (4.15.6-1 -> 4.15.9-1)
[2018-04-11 19:51] [ALPM] upgraded linux (4.15.9-1 -> 4.15.15-1)
```

According to what I can find, Arch Linux basically uses the vanilla Linux kernel source with only a few patches applied, no of which seem to pertain to rtlwifi: https://git.archlinux.org/svntogit/packages.git/tree/trunk?h=packages/linux
(Sourced from a forum post: https://bbs.archlinux.org/viewtopic.php?id=147502)

One note is that I don't think the problem is necessarily with the WPA2 encryption since my 2.4GHz connection also uses it, and I'm able to connect to that successfully.

**Comment by warrenpw** [comment]
Interestingly enough, I saw different behavior today when attempting to connect to the 5GHz network: it seems that a link was able to be established twice, but only for a short period of time; within around 10-20 seconds the link would drop and a reconnect would be attempted.
However, despite a connection being made for a small amount of time, attempts to ping 8.8.8.8 would report "Network is unreachable", and attempting to check the interface IP with ip addr show reveals that no IPv4 address is being assigned; maybe no data is flowing despite the connection, so no DHCP requests or responses can be made?

Dmesg output from the initial established link and subsequent reconnect: 
[dmesg_reconnect.txt](https://github.com/lwfinger/rtlwifi_new/files/1945331/dmesg_reconnect.txt)


ip addr show while connected:
[ip_addr_show.txt](https://github.com/lwfinger/rtlwifi_new/files/1945332/ip_addr_show.txt)

**Comment by ss32** [comment]
Same issue here, just pulled and built the newest drivers but no change.  The 5GHz network shows up but the card fails to connect.

```
lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.3 Sylvia
Release:	18.3
Codename:	sylvia


uname -r
4.12.0-041200-generic

lspci | grep Wireless
08:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8812AE 802.11ac PCIe Wireless Network Adapter (rev 01)
```

**Comment by lwfinger** [comment]
You have left too little information to get any help. On my system, either the mainline driver or the extended branch of this repo make 5 GHz connections without problems.

**Comment by ss32** [comment]
What information do you need?  This should help - https://pastebin.com/wQZr1w1f

Does the 8821 driver work for 8812?  I noticed my system loading the 8821 driver.

**Comment by lwfinger** [comment]
The info you provided, particularly the dmesg output helped. In particular,

[   15.548081] wlp8s0: authenticate with <MAC 'FBI_Van_34' [AN3]>
[   15.549150] wlp8s0: send auth to <MAC 'FBI_Van_34' [AN3]> (try 1/3)
[   15.570201] wlp8s0: authenticated
[   15.570294] wlp8s0: associating with AP with corrupt probe response
[   15.571542] wlp8s0: associate with <MAC 'FBI_Van_34' [AN3]> (try 1/3)
[   15.600635] wlp8s0: RX AssocResp from <MAC 'FBI_Van_34' [AN3]> (capab=0x411 status=0 aid=7)
[   15.600838] wlp8s0: associated
[   15.600845] IPv6: ADDRCONF(NETDEV_CHANGE): wlp8s0: link becomes ready
[   76.988991] IPv6: ADDRCONF(NETDEV_UP): enp5s0: link is not ready
[   82.262556] wlp8s0: deauthenticating from <MAC 'FBI_Van_34' [AN3]> by local choice (Reason: 3=DEAUTH_LEAVING)
[   84.761490] wlp8s0: authenticate with <MAC 'Mom's Basement' [AN18]>
[   84.762374] wlp8s0: send auth to <MAC 'Mom's Basement' [AN18]> (try 1/3)
[   84.864816] wlp8s0: send auth to <MAC 'Mom's Basement' [AN18]> (try 2/3)
[   84.968795] wlp8s0: send auth to <MAC 'Mom's Basement' [AN18]> (try 3/3)
[   85.072791] wlp8s0: authentication with <MAC 'Mom's Basement' [AN18]> timed out

Which of these two AP's are you trying to connect with? Please run one other command:

sudo iw dev wlp8s0 scan | egrep "SSID|signal|DS Parameter set"

Post the output. The code for 8812 is a little different than for the 8821, but the 8821 driver takes that into account.

**Comment by ss32** [comment]
Mom's Basement is the 5Ghz.  I'll get back to you with the output when I get off of work.

**Comment by ss32** [comment]
```
$ sudo iw dev wlp8s0 scan | egrep "SSID|signal|DS Parameter set"
[sudo] password for scott: 
	signal: -62.00 dBm
	SSID: FBI_Van_34
	DS Parameter set: channel 11
	Extended capabilities: SSID List, WNM-Notification
	signal: -48.00 dBm
	SSID: FBI_Van_34_Ext
	DS Parameter set: channel 11
	signal: -60.00 dBm
	SSID: ASUS
	DS Parameter set: channel 11
	signal: -74.00 dBm
	SSID: sedley
	DS Parameter set: channel 6
	Extended capabilities: TFS, WNM-Sleep Mode, TIM Broadcast, BSS Transition, SSID List, 6
	signal: -74.00 dBm
	SSID: xfinitywifi
	DS Parameter set: channel 6
	signal: -78.00 dBm
	SSID: BazookaJoe
	DS Parameter set: channel 6
	signal: -71.00 dBm
	SSID: 
	DS Parameter set: channel 6
	Extended capabilities: SSID List, 6
	signal: -74.00 dBm
	SSID: DIRECT-C7-HP OfficeJet Pro 6970
	DS Parameter set: channel 11
	signal: -77.00 dBm
	SSID: Mom's Basement
	DS Parameter set: channel 48
	Extended capabilities: SSID List, WNM-Notification
```

**Comment by lwfinger** [comment]
Wifi is a half-duplex medium, and at any particular time, only one station can be transmitting. The repeater needs to rebroadcast everything, thus the amount of transmit traffic from the linked AP is effectively doubled.

**Comment by TheBronx** [comment]
Just managed to connect to a 5GHz WPA2 network with an Asus PCE-AC51 card, or in other words a **rtl8812ae**. Using latest version of rtlwifi_new as of today.
On Kubuntu 17.04 with kernel 4.10.0

Before installing this driver I couldn't connect to the 5G network at all.

Unfortunately after a couple minutes the connection went down. Not sure why. I found this in the syslog:

    Aug  7 22:04:20 salva-kde wpa_supplicant[1242]: wlp35s0: CTRL-EVENT-SCAN-FAILED ret=-16 retry=1
    Aug  7 22:04:50 salva-kde wpa_supplicant[1242]: message repeated 30 times: [ wlp35s0: CTRL-EVENT-SCAN-FAILED ret=-16 retry=1]
    Aug  7 22:04:51 salva-kde wpa_supplicant[1242]: wlp35s0: CTRL-EVENT-SCAN-FAILED ret=-16 retry=1
    Aug  7 22:06:24 salva-kde wpa_supplicant[1242]: message repeated 93 times: [ wlp35s0: CTRL-EVENT-SCAN-FAILED ret=-16 retry=1]

I ended up disconnecting and reconnecting manually.

After 15 minutes it disconnected again:

    Aug  7 22:18:09 salva-kde wpa_supplicant[1242]: wlp35s0: WPA: Group rekeying completed with 2c:4d:54:b7:bc:bc [GTK=CCMP]
    Aug  7 22:18:29 salva-kde wpa_supplicant[1242]: wlp35s0: CTRL-EVENT-SCAN-FAILED ret=-16 retry=1

This time I haven't done anything manually. After a few minutes, not sure exactly, maybe 3 minutes, the connection is working again.

I know it's quite unstable but still, good job with this driver. Seriously, after trying to install the Realtek one and facing lots of problems (because of Ubuntu and because of compilation errors on the C code for the driver...) yours installed without any issues. 

So if there is anything I can do to help let me know! :smiley:

**Comment by lwfinger** [comment]
You can debug the problem. As it does not happen on my system, you need to determine if the problem is some incompatibility between the driver and YOUR access point, the problem is something wrong with the Ubuntu user-space code, or your hardware is faulty.

To isolate these two potential problems, do the fiollowing:
1. Go to https://software.opensuse.org/distributions/leap and download the live version of Leap 15.0. It will not matter if you select the KDE or Gnome version (I used KDE).
2. Burn that .iso to a USB stick using dd (sudo dd if=<downloaded_file_name> of=/dev/sdb bs=64M. If the blank USB stick appears at some other drive than sdb, adjust appropriately.
3. Boot the USB stick to the "live" version.
4. Using the NetworkManager connection utility, connect to your 5G network.
5. Test. I connected to a Netgear WNDR3400 router using channel 153 and tested for essentially 1 hour. I ran a ping to the router's address. No packets were dropped, and the connection was never lost.

Analyze the results: If your results match mine, then the problem is with Ubuntu. You can take up the issue with them, or switch to openSUSE Leap 15.0 Gnome. Your choice. If you are still getting drops, then you need to post exactly what make and model of access point you are using, and what version of firmware it is running. At this point, the Realtek people will try to duplicate your findings to determine if the driver is incompatible, or if your hardware is faulty. It will likely be necessary to set up a second system capturing the over-the-air packets.
