### ISSUE TITLE
Instalation for RTL8723de works fine, but can't connect

### ISSUE THREAD

**Issue by vagostep** [lwfinger/rtlwifi_new#356]
I can't get connect to a WIFI network. The password is correct. The dmesg throw this: 

[  241.765076] IPv6: ADDRCONF(NETDEV_UP): wlo1: link is not ready
[  243.318995] wlo1: authenticate with c4:e9:84:ed:db:86
[  243.337245] wlo1: send auth to c4:e9:84:ed:db:86 (try 1/3)
[  243.440885] wlo1: send auth to c4:e9:84:ed:db:86 (try 2/3)
[  243.544862] wlo1: send auth to c4:e9:84:ed:db:86 (try 3/3)
[  243.648912] wlo1: authentication with c4:e9:84:ed:db:86 timed out
[  250.753895] wlo1: authenticate with c4:e9:84:ed:db:86
[  250.773203] wlo1: send auth to c4:e9:84:ed:db:86 (try 1/3)
[  250.877291] wlo1: send auth to c4:e9:84:ed:db:86 (try 2/3)
[  250.980839] wlo1: send auth to c4:e9:84:ed:db:86 (try 3/3)
[  251.084891] wlo1: authentication with c4:e9:84:ed:db:86 timed out
[  252.594412] wlo1: authenticate with c4:e9:84:ed:db:86
[  252.613475] wlo1: send auth to c4:e9:84:ed:db:86 (try 1/3)
[  252.716929] wlo1: send auth to c4:e9:84:ed:db:86 (try 2/3)
[  252.820892] wlo1: send auth to c4:e9:84:ed:db:86 (try 3/3)
[  252.925264] wlo1: authentication with c4:e9:84:ed:db:86 timed out
[  254.934624] wlo1: authenticate with c4:e9:84:ed:db:86
[  254.953118] wlo1: send auth to c4:e9:84:ed:db:86 (try 1/3)
[  255.057317] wlo1: send auth to c4:e9:84:ed:db:86 (try 2/3)
[  255.160883] wlo1: send auth to c4:e9:84:ed:db:86 (try 3/3)
[  255.264893] wlo1: authentication with c4:e9:84:ed:db:86 timed out
[  266.900022] IPv6: ADDRCONF(NETDEV_UP): wlo1: link is not ready
[  267.353719] IPv6: ADDRCONF(NETDEV_UP): wlo1: link is not ready

**Comment by lwfinger** [comment]
Perhaps you have one of those RTL8723DE cards with only one antenna and a misconfigured EFUSE. HP sent lots of RTL8723BE cards out that way and similar behavior is reported for the DE as well.

Run the command 
sudo iw dev wlo1 scan | egrep "SSID|signal" and post the output.

**Comment by lwfinger** [comment]
Those signal strengths indicate that you have only ONE antenna and that it is NOT connected to the post indicated by the EFUSE. As only the factory could have changed that setting in the EFUSE, then we have to change the setup either by opening the computer and moving the antenna to the other post (which will break Windows) or by using the ant_sel parameter. To do this, run
"sudo edit /etc/modprobe.d/50-rtl8723de.conf" and add a line that says "options rtl8723de ant_sel=2". Now do a COLD reboot - the power must be completely off otherwise the card will retain the old antenna settings, and negate the findings. Now run the command from the previous step. If you still cannot connect, change the line in /etc/modprobe.d/50-rtl8723de.conf to have "ant_sel=1". Repeat the reboot, etc. If you still do not have a connection, then post the strengths for the two ant_sel trials.

**Comment by vagostep** [comment]
I have dual boot, and in Windows works well. Doing this configuration would not break anything in Windows?

**Comment by lwfinger** [comment]
Think about that question a bit more. Do you know of any case where a software change would affect the other OS in a dual-boot system? I do not.

**Comment by vagostep** [comment]
Asked for precautions, no more. Ready! It's works fine. Thanks for the support

**Comment by ppeapen** [comment]
Thanks @lwfinger.  This solution worked for me - 8 months after buying my HP laptop! I had to set ant_sel=1.
