### ISSUE TITLE
cc1: error: code model kernel does not support PIC mode

### ISSUE THREAD

**Issue by rizwan92** [lwfinger/rtlwifi_new#390]
ubuntu 18.04 bionic 
wifi driver rtl8723be

i ran this commands in the terminal
```
git clone https://github.com/lwfinger/rtlwifi_new.git
cd rtlwifi_new
git checkout extended
sudo make install
```
`make command not found :`

then i ran 
```
sudo apt-get install --reinstall make
 sudo apt-get install build-essential
```

error: 

```
 sudo make install
make -C /lib/modules/4.15.0-33-generic/build M=/home/rizwan/Downloads/rtlwifi_new modules
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-33-generic'
Makefile:976: "Cannot use CONFIG_STACK_VALIDATION=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel"
  CC [M]  /home/rizwan/Downloads/rtlwifi_new/base.o
cc1: error: code model kernel does not support PIC mode
scripts/Makefile.build:332: recipe for target '/home/rizwan/Downloads/rtlwifi_new/base.o' failed
make[2]: *** [/home/rizwan/Downloads/rtlwifi_new/base.o] Error 1
Makefile:1552: recipe for target '_module_/home/rizwan/Downloads/rtlwifi_new' failed
make[1]: *** [_module_/home/rizwan/Downloads/rtlwifi_new] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-33-generic'
Makefile:87: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by lwfinger** [comment]
You have not included all the necessary packages. Follow the instructions in the error message.

**Comment by rizwan92** [comment]
installed those modules now still i am getting the same error

```
rizwan@rizwan-HP:~/Downloads/rtlwifi_new$ sudo make
make -C /lib/modules/4.15.0-33-generic/build M=/home/rizwan/Downloads/rtlwifi_new modules
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-33-generic'
  CC [M]  /home/rizwan/Downloads/rtlwifi_new/base.o
cc1: error: code model kernel does not support PIC mode
scripts/Makefile.build:332: recipe for target '/home/rizwan/Downloads/rtlwifi_new/base.o' failed
make[2]: *** [/home/rizwan/Downloads/rtlwifi_new/base.o] Error 1
Makefile:1552: recipe for target '_module_/home/rizwan/Downloads/rtlwifi_new' failed
make[1]: *** [_module_/home/rizwan/Downloads/rtlwifi_new] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-33-generic'
Makefile:87: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by rizwan92** [comment]
i installed those modules using command
`sudo apt install libelf-dev  libelf-devel elfutils-libelf-devel`
only libelf-dev gets installed but remaining two is unbale to locate 
```
rizwan@rizwan-HP:~$ sudo apt install libelf-dev  libelf-devel elfutils-libelf-devel
[sudo] password for rizwan: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libelf-devel
E: Unable to locate package elfutils-libelf-devel
rizwan@rizwan-HP:~$ 

```
anyway now its is not asking for to please install libelf-dev, libelf-devel or elfutils-libelf-devel" look at  in my above question
but the error is still same 
`cc1: error: code model kernel does not support PIC mode`

**Comment by lwfinger** [comment]
The libelf development code is called by different names depending on distro. It is expected that you will have only one of them.

The non-support of PIC mode is due to the compiler that your distro has included. You need to complain to them. In fact, they may have an alternative repository from which you can download the correct compiler. In any case, there is nothing wrong with the driver code, and nothing that I can fix.

**Comment by rizwan92** [comment]
i installed the extended branch in my ubuntu 18.04  but signal is very weak help me?

**Comment by lwfinger** [comment]
The problem is that your vendor only installed one antenna. That saved them a few pennies. The problem is that they failed to encode the EFUSE correctly. That information says that the antenna is actually connected to the other connector. You have two ways to fix it. (1) Open the case and physically move the wire to the other connector. Although that will fix Linux, it will break Windows. (2) Use the ant_sel module option to oveeride the EFUSE setting. To do this, run the following command:

sudo iw dev wlan0 scan | egrep "SSID|signal"

If your wireless device is not wlan0, adjust the command accordingly. Note the signal strength for your AP. If that value is about -80 dBm, then you have the wrong antenna selected problem. With a signal less than -60 dBm, the connection will not be stable.

Next run the command

sudo su - && echo "options rtl8723be ant_sel=2" > /etc/modprobe.d/50-rtl8723be.conf

Next, do a cold reboot. The power MUST be completely off for a few seconds, otherwise the chip may retain to old information. After rebooting, run the "sudo iw ..." command again. If the signal is now -55 or higher, you are done. If not, rerun the echo sequence with ant_sel=1, cold reboot, and do the scan again.

**Comment by tanmayakp** [comment]
I got one working solution.
Use gcc-5
These are the steps:
Install gcc-5 and export or make link to make gcc-5 default.
**$sudo apt install gcc-5
$sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc**

Download the repo:
**$git clone https://github.com/lwfinger/rtlwifi_new.git
$cd rtlwifi_new
$git checkout origin/extended -b extended**
Clean the repo once before compiling.
**$make clean
$sudo make install
$sudo modprobe -r rtl8723be &&  sudo modprobe  rtl8723be**

**Comment by niranjanbhuta** [comment]
Sir, my model is rtl8188ftv which is not listed in this depository. How to add it?

**Comment by lwfinger** [comment]
This thread is not a good one to pose this question as it would be hard to find in a search. Please open a new one with your device name in the subject. The other thing needed would be the device ID. If this is a USB device, then use the lsusb command to find the ID. If PCI, then use 'lspci -nn'.

From a quick search, I think this is a USB device with ID 0bda:f179.

Once I know those values, then it will be easy to add the device to the driver 8188eu table, but the driver may not work very well as the 8188F devices may be very different from the 8188E. There is also a driver at https://github.com/lutmm/rtl8188fu. My impression is that will require a lot of work to compile on newer kernels.
