### ISSUE TITLE
rtlwifi-next issue, looking for someone with knowledge on it.

### ISSUE THREAD

**Issue by Vlku272** [lwfinger/rtlwifi_new#394]
The rtlwifi-next github is basically dead so I came here since I'm assuming this github is basically the same but with slightly different drivers. Post is here on that github:
https://github.com/rtlwifi-linux/rtlwifi-next/issues/11
New to linux so when a problem comes up I'm pretty much hopeless so just looking for some help/knowledge.

**Comment by lwfinger** [comment]
That other repo is derived from this one. I have no idea who forked it, and what they were trying to accomplisk; however, the problem you faced there was fixed here long ago. I keep these drivers up to date with the kernel, and I fix them so that they will build on the newest kernels.

**Comment by Vlku272** [comment]
I need the drivers for rtl8822be specifically and they don't seem to be supported here which is why I've been trying to use that repo

**Comment by lwfinger** [comment]
Whenever you use a repo, you always need to know what branches are available. The driver you want is in the extended branch. You are in the master branch. How to get there has been discussed several times. Google for 'git branch checkout' to see how to do it.

**Comment by Vlku272** [comment]
ok so I'm installing the drivers via usb because the computer that needs it has no internet yet, I got up to `sudo make install` which threw an error, I fixed that with with a solution i found online which was to add `-no-pie` to the command, and now I'm up to `sudo modprobe -r <>` and I'm not sure what I'm supposed to be looking for with `lspci` and `grep Wireless` doesnt seem to work. I tried rtl8822be and RTS522A (which was one of the things in `lspci` listed under the realtek entry) and both said Module could not be found.

**Comment by lwfinger** [comment]
I understand that it will be difficult to post actual output due to the lack of internet, but I'm not sure what you are doing. Having the output of 'lspci -nn' is necessary. As you have no connectivity, you probably downloaded a zip file. Is that correct? If so, which branch did you get?

Remember "man" is your friend. The command "modprobe -r <>" is to REMOVE a driver. If one has not been loaded, what did you expect?

As you do not report the error with "make install", I'm not sure what you needed to do, but I seriously doubt that using -no-pie was the correct solution.

Let me see every step. While logged in as an ordinary user (not root), change directory to the one with the source and do the following:

sudo make clean
ls > log.txt
lspci -nn >> log.txt 2>&1
make >> log.txt 2>&1
sudo make install >> log.txt 2>&1
sudo modprobe -v rtl8822be >> log.txt 2>&1

Finally, copy file log.txt to a USB stick, move the stick to a system with internet access, copy that file to a pastebin account, and post a link here. The use of the ">" symbol in the above commands redirects the output to a file. Using ">>" means to append to that file. The strange "2>&1" tells the system to output error information to the file as well. With those commands, you will see nothing on the screen.

**Comment by Vlku272** [comment]
Ok finally got around to it, using that method everything seems to work except make doesn't load properly while trying to output to log.txt, and now my problem is that now `sudo modprobe -v rtl8822be` returns `modprobe: ERROR: could not insert 'rtl8822be': Required key not available
insmod /lib/modules/4.15.0-29-generic/kernel/drivers/net/wireless/realtek/rtlwifi/rtlwifi.ko` in the log. Attached is the entire log minus the section made by `make` because it won't run while outputting to the log at all.
[log.txt](https://github.com/lwfinger/rtlwifi_new/files/2348402/log.txt)

**Comment by Vlku272** [comment]
all good now, turns out kubuntu auto installs the drivers but the automatic install was also being blocked by the secure boot thing, thanks for the help!

**Comment by lwfinger** [comment]
Just to clarify the terminology - it uses dkms to "autoinstall" the drivers.

**Comment by skyh24** [comment]
i used rtl_next, i doesn't work.  and i came here, i found 8822be in the extended branch. i compile the code. but i still cannot modprobe 8822be, require the ??. however i open the uelf insecure mode and modprobe 8823be, and the wifi is working.

**Comment by Vlku272** [comment]
I guess if your wifi is working you don't really have a problem lol

**Comment by lwfinger** [comment]
As we cannot sign the modules, if you use secure boot, the load will fail. End of story!!

**Comment by zhangsd20** [comment]
hi，
   rtl8822be can work on openwrt ？

**Comment by lwfinger** [comment]
It should. What CPU are you going to use?

**Comment by zhangsd20** [comment]
Hi，
    [    0.000000] SoC: Qualcomm Atheros QCA9558 ver 1 rev 0













在2019年02月01 00时57分，"lwfinger"<notifications@github.com>写道：

It should. What CPU are you going to use?

**Comment by lwfinger** [comment]
Is that MIPS processor big- or little-endian? I'm not sure that this driver has ever been tested with big-endian architecture. I can test USB devices on my PowerMac G4, but it has no PCIe bus.

The place that I would worry about is reading the EFUSE. That would certainly cause the chip type to be wrong.
