### ISSUE TITLE
rtl8192cu warns that nl80211_authenticate causes sleep in atomic context

### ISSUE THREAD

**Issue by brentinrochester** [lwfinger/rtlwifi_new#413]
I'm using the USB rtlwifi/rtl8192cu driver.  It works well, except it throws a warning every time it authenticates.  The backtrace of the warning is attached:
[sleep_from_atomic.log](https://github.com/lwfinger/rtlwifi_new/files/2484926/sleep_from_atomic.log)

In the call tree under nl80211_authenticate() it eventually gets to:  rtl_ips_nic_on()

This function starts with: 
`cancel_delayed_work_sync(&rtlpriv->works.ips_nic_off_wq);`

But during the authentication call chain, I'm always in an atomic state, so the kernel warns me:
```
BUG: sleeping function called from invalid context at /home/me/m300_wifi/linux/kernel/kernel/workqueue.c:2793
in_atomic(): 1, irqs_disabled(): 0, pid: 1471, name: wpa_supplicant
``` 

If I change to the call to the non-sync cancel_delayed_work(), the warning goes away, but I'm not waiting for the work queue to finish and flush.  I'm not sure what the impact of that would be, but it seems like it could cause problems in other call chains. 

I suspect a better approach is in for the driver to flush the work queues before becoming atomic. That change could be possibly be localized to the authenticate. 

Any guidance you can give would be greatly appreciated.

**Comment by brentinrochester** [comment]
I uploaded a potential fix for this to https://github.com/brentinrochester/rtlwifi_new/pull/1

It definitely fixes the problem.  I'm not sure if there would be any negative consequences.

**Comment by lwfinger** [comment]
As I said in the other thread, adding calls to in_atomic() are frowned upon.

Try the following patch instead:

diff --git a/core.c b/core.c
index 22bb86d..2ec763b 100644
--- a/core.c
+++ b/core.c
@@ -633,7 +633,6 @@ static int rtl_op_config(struct ieee80211_hw *hw, u32 changed)
        if (mac->skip_scan)
                return 1;
 
-       mutex_lock(&rtlpriv->locks.conf_mutex);
        if (changed & IEEE80211_CONF_CHANGE_LISTEN_INTERVAL) {  /* BIT(2)*/
                RT_TRACE(rtlpriv, COMP_MAC80211, DBG_LOUD,
                         "IEEE80211_CONF_CHANGE_LISTEN_INTERVAL\n");
@@ -654,6 +653,7 @@ static int rtl_op_config(struct ieee80211_hw *hw, u32 changed)
                        rtl_ips_nic_on(hw);
        }
 
+       mutex_lock(&rtlpriv->locks.conf_mutex);
        /*For LPS */
        if ((changed & IEEE80211_CONF_CHANGE_PS) &&
            rtlpriv->psc.swctrl_lps && !rtlpriv->psc.fwctrl_lps) {

I think the mutex was locked too early, which should be fixed by moving it.
