### ISSUE TITLE
Possible memory leak in rtl_pci

### ISSUE THREAD

**Issue by fireio** [lwfinger/rtlwifi_new#414]
Using custom compiled kernel (to enable kmemleak debug and debug symbols)
4.18.14-arch1-1-kmemleakdebug GNU/Linux

Over a day, a significant amount of memory was observed to be [lost](https://www.reddit.com/r/archlinux/comments/9p5b2w/unable_to_determine_whats_taking_up_memory/)

[kmemleak.log](https://github.com/lwfinger/rtlwifi_new/files/2499421/kmemleak.log)

Seems to be in allocated [here](https://github.com/torvalds/linux/blob/024ddc0ce1049298bd3cae60ae45d9c5f0fb8b9c/drivers/net/wireless/realtek/rtlwifi/pci.c#L802)

Can you confirm if that allocation is freed in all cases?
I see free only in the "else" clause [here](https://github.com/torvalds/linux/blob/024ddc0ce1049298bd3cae60ae45d9c5f0fb8b9c/drivers/net/wireless/realtek/rtlwifi/pci.c#L829).

**Comment by fireio** [comment]
Stefan writes "I did not see this with 4.18"
The specific one I'm talking about is on 4.18.14
Is it still the same?

**Comment by lwfinger** [comment]
It only happens if you use wireless extensions such as iwconfig and the associated ioctl calls. If you use iw and the modern tools, then you do not have the problem. At the moment, all kernels past 4.17 have this problem, even though the fix is known due to a misunderstanding regarding a technical annotation of the patch. That has been fixed, and the patch should appear in both mainline and stable kernels shortly.

Yes, 4.18.14 will have the problem if you use the deprecated tools.

**Comment by fireio** [comment]
I just have a gnome NetworkManager. Probably that uses old calls. Let me know what version you think is fixed, when it's fixed, or let me know if I can provide any more info / run any more tests

**Comment by fireio** [comment]
Still happening on 4.19.1

**Comment by lwfinger** [comment]
Of course. The patch is in the pipeline. Once it reaches kernel HEAD, it will be backported. When will that happen? Your guess is a good as mine. I have done all I can and it is now in the hands of the upstream maintainers.
