### ISSUE TITLE
Any Chance to Get the Driver Off-line?

### ISSUE THREAD

**Issue by lhy-loveworld** [lwfinger/rtlwifi_new#417]
Hi, recently I bought a new computer with realtek 8822be. And I cannot use the ethernet connection. Can I got the deb package of the driver? Thanks!

**Comment by lwfinger** [comment]
No, at least from me. I provide the source for the drivers so that each user can build their own. That is necessary because EVERY combination of kernel source and compiler version would be needed to provide a binary package. If I wanted to do a binary package, I would be inclined to provide an rpm, which is what my distro uses.

A little nitpick: Language is important - the RTL8822BE is a wireless device, not an Ethernet one. If your distro provides a 4.18.x or 4.19.x kernel, there is a driver for the 8822be. My repo has a newer one that is not yet in the kernel, but that one works.
