### ISSUE TITLE
modprobe: ERROR: could not insert 'rtl8723de': Invalid argument

### ISSUE THREAD

**Issue by nithin-84** [lwfinger/rtlwifi_new#453]
once i succesfully installed it.
one day suddenly the wifi icon dissappeared..
and i repeted from the beginning by deleting the rtlwifi folder
and it ended up with this error code :

nithin@nithin:~/rtlwifi_new$ sudo modprobe rtl8723de
modprobe: ERROR: could not insert 'rtl8723de': Invalid argument
nithin@nithin:~/rtlwifi_new$

**Comment by lwfinger** [comment]
You probably got a new kernel, which is why the wifi disappeared. When you use an external module, you MUST rebuild using 'male' and 'sudo make install' EVERY time the kernel changes.

In the output of the dmesg command, you will see what invalid argument was reported. If it disagrees with the symbol layout, you have built the driver with the wrong headers. They must match the running kernel EXACTLY. The first line after the make command is something like
`make -C /lib/modules/5.1.0-rc7/build M=/home/finger/rtlwifi_new1 modules`
The part between "modules/" and "/build" must be the same as the output of the "uname -r" command. There can be NO differences.

**Comment by ptsubin** [comment]
I am having the same issue on Fedora 29 after upgrading to kernel 5.0.14-200.fc29.x86_64. Initially it was operation not permitted. Signing the modules and enrolling the keys changed the error message to Invalid Argument. There are no new lines in dmesg when this happens. 
```
uname -r
5.0.14-200.fc29.x86_64
rtlwifi_new]$ make
make -C /lib/modules/5.0.14-200.fc29.x86_64/build M=/home/subin/Experiments/rtlwifi_new modules
make[1]: Entering directory '/usr/src/kernels/5.0.14-200.fc29.x86_64'
```
When the modules were not signed, dmesg had the error log. Build went fine too. But no luck inserting it.

**Comment by lwfinger** [comment]
Actually showing an actual error message would be helpful.

**Comment by ptsubin** [comment]
> Actually showing an actual error message would be helpful.

Apart from "modprobe: ERROR: could not insert 'rtl8723de': Invalid argument" there are no other errors seen. modprobe -vvv also doesn't show other errors. No errors are seen in dmesg. I am not sure what else to try to find out what is actually happening. strace wan't very helpful. 

Please let me know if there is anything else I can try/any other logs to be shared. I will do.

**Comment by ptsubin** [comment]
So, the problem is only with .ko.xz modules. I went back to the 4.18 kernel. Built and installed the kernel modules. Signed them and got the same error. I did uninstall and then installed again, and this time, for some reason, the module files were not compressed. They are simple .ko files. I am not sure how that happened. I did nothing. I signed the rtl8723de and all its dependencies and did a modprobe. No errors. And WiFi is on.

**Comment by lwfinger** [comment]
Are the rest of your modules compressed. The Makefile tries to agree with the rest of the system, but there may be an error in that code.

**Comment by SarmadEdward** [comment]
Thanks for the blog
I have a new computer: 
Ubuntu 19.04 Lenovo and realtek, it started earlier when compiling under 5.0.0.13, I was getting problems with "ieee80211_rate_control_register" failure with som ret_val

Today I upgraded to Kernel 5.0.0.15, probably I tried some tweaks, I started getting this message "could not insert 'rtl8723de':  invalid argument" when "modprobe"

However insmod doesn't show any failure

lshw shows "DISABLED" before insmod, "UNCLAIMED" after insmod
I do fconfig wlp7s0 up, I get the chip "enabled", of course with MAC but no IP

Please, can you tell what was the last Kernel that the github up-to-date code was working on?
I am downgrading to an old kernel, and compiling the drive with that kernel as a work around until things go well on your side.
Thanks

**Comment by lwfinger** [comment]
The last working kernel is 5.2.0-rc0, i.e. the very latest! Any problems you are having are not due to the kernel. There has been a report that the modules are failing when compressed, but that is not verified.

Do you have secure boot enabled?

When you do the command ls /lib/modulles/$(uname -r)/kernel/drivers/net/', is there a suffix after ".ko"?

**Comment by SarmadEdward** [comment]
Larry
1- Disabled secure boot since the beginning
2- If you mean ko.xz drivers inside /lib/modules/$kernel/drivers/net that may conflict your code, no, both kernels have only *.ko
My last 2 dmesg logs show
[  335.030697] PKCS#7 signature not signed with a trusted key
[  335.031090] rtl8723de: `X' invalid for parameter `ant_sel'

Is that a requirement for digital signature of a module in the new kernels? In new motherboards?

When I coded some USB OTG modules, We had to have some of them signed, I wonder whether this is the real issue.

**Comment by SarmadEdward** [comment]
I think that I could find a path
(git clone, checkout, pull,  make, make install)

copy those files to /lib/module/$(uname -r)
halmac.ko, rtl8723de.ko and rtl8822be.ko

I have to start by (due to dependency)
rmmod halmac
rmmod r8822be

insmod halmac.ko
insmod rtl8723de.ko ant_sel=1 (or 2) .. btw modprobe doesn't work because ant_sel=X is not accepted from the kernel - can you fix?)
insmod r8822be.ko

ifconfig wlp7s0 up ((bring wifi adapter up))
Now lshw shows that the adapter is running

But the good news is all the modules in this sequence are in (lsmod | grep rtl)

And the bad news is: there is nothing "depending on them in lsmod right column", I believe that I am missing some command in the network stack.
Consequently: Still restarting networking / network-managerd didn't resolve the problem

**Comment by lwfinger** [comment]
"insmod rtl8723de.ko ant_sel=1 (or 2) .. btw modprobe doesn't work because ant_sel=X is not accepted from the kernel - can you fix?)" - NO. You need to search the files in /etc/modprobe/d/, find the file that mentions rtl8723de and removes the "ant_sel" option. It is not something I did - you did it to yourself.

**Comment by lwfinger** [comment]
It should not be necessary to have the module signed as long as secure boot is off. I think that message is informational.

The message "[ 335.031090] rtl8723de: X' invalid for parameter ant_sel'" means you have a faulty value in an options file in /etc/modprobe.d/. I use a symbolic value in the documentation, but the actual value should be 0, 1, or 2. Zero is the same as having no option. Note that insmod does not interrogate the options files that way that modprobe does. If removing that "ant_sel=X" does not fix the problem, then do

**Comment by ptsubin** [comment]
> Are the rest of your modules compressed. The Makefile tries to agree with the rest of the system, but there may be an error in that code.

Yes, the rest of the modules are compressed in the system. I guess I should have uncompressed the module, sign and then compress it back. But a make uninstall and a make install installs uncompressed modules anyway and I just signed them with the enrolled key.
