### ISSUE TITLE
regression RTL8192CU 4.xx kernels (doesn't work at all), but works 3.19.x kernels

### ISSUE THREAD

**Issue by deri82** [lwfinger/rtlwifi_new#47]
I have a box which I connect wia wifi.

the wifi device is

Bus 003 Device 003: ID 0586:341f ZyXEL Communications Corp. NWD2205 802.11n Wireless N Adapter [Realtek RTL8192CU]

since 4.0 kernel there has been a regression that causes it not to work at all. It works at 3.19.7 and earlier 3.19 series. 

4.0 kernel changes

Chun-Yeow Yeoh (1):
      rtl8192cu: fix the mesh beaconing

Taehee Yoo (2):
      rtlwifi: add support to send beacon frame.
      rtlwifi: rtl8192cu: Set fw_ready flag

Larry
      rtlwifi: rtl8192cu: Rework calls to rate-control routine

Something broke it. It works when reverted back kernel.

**Comment by deri82** [comment]
Cant use 4 serie kernels at all because of this regression.

**Comment by lwfinger** [comment]
Can you at least bisect to help find the problem?

**Comment by deri82** [comment]
I could download the kernel, but how do I find the exact commit numbers and revert them?

**Comment by lwfinger** [comment]
Study 'git bisect --help'.

**Comment by Borgvall** [comment]
I am also affected by this regression. The symptom is, that NetworkManager claims the wifi is connected. However the interface is not getting configured, making the connection useless.

I bisect this issue:
first bad commit: [9c1c98a3bb7b7593b60264b9a07e001e68b46697] mac80211: Send EAPOL frames at lowest rate

Maybe the lowest rate triggers a bug in the driver?

**Comment by deri82** [comment]
Is that the only commit you need to revert to get it working?

**Comment by Borgvall** [comment]
Yes, it is.

**Comment by lwfinger** [comment]
Once more, for repos with multiple branches, please indicate which one you are using. Yes, it does make a difference.

Just to confirm. If you checkout v4.1 of the kernel and revert commit 9c1c98a, does the latest version of this repo work?

Second question: Have you tried using the driver in the kernel? Does it also need the reversion?

**Comment by Borgvall** [comment]
I used the kernel git branch master (git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git) for bisecting, including the rtwifi drivers in the kernel tree. I confirm that using that branch, checkout the tag `v4.1`, reverting 9c1c98a, building and booting, results in a stable wifi connection.

I have not tried any combinations of git kernel with out of tree `rtlwifi_new`.

**Comment by lwfinger** [comment]
Because you posted here, I thought you were using this repo.

**Comment by lwfinger** [comment]
I'm not sure what the difference is, but rtl8192cu on my system connects to an 802.11ac router using WPA2 just fine with no reversions to the standard code. This is an openSUSE 13.2 x86_64 system using NetworkManager 0.9.10, wpa_supplicant 2.2, and kernel 4.2-rc1.

**Comment by Borgvall** [comment]
I am using Fedora 22 x86_64. The router is 'Speedport W 701V' using mixed 802.11b+g and wpa-psk (tkip) for encryption. The level is quite low ~-65dB. NetworkManager 1.0.2, wpa_supplicant 2.4.

**Comment by lwfinger** [comment]
I cannot emulate that weak signal; however, my system connects quickly to a WPA-PSK(TKIP) router. That is WPA1. I'm not sure what I can do for you. The driver works with the lowest rate. All management frames are sent at that rate.

Below is an excerpt of /var/log/wpa_supplicant.log:

wlp0s20u5: SME: Trying to authenticate with 00:1a:70:46:ba:b1 (SSID='Larry_wpa1' freq=2462 MHz)
wlp0s20u5: Trying to associate with 00:1a:70:46:ba:b1 (SSID='Larry_wpa1' freq=2462 MHz)
wlp0s20u5: Associated with 00:1a:70:46:ba:b1
wlp0s20u5: WPA: Key negotiation completed with 00:1a:70:46:ba:b1 [PTK=TKIP GTK=TKIP]
wlp0s20u5: CTRL-EVENT-CONNECTED - Connection to 00:1a:70:46:ba:b1 completed [id=0 id_str=]
wlp0s20u5: CTRL-EVENT-SCAN-STARTED 
wlp0s20u5: CTRL-EVENT-SCAN-STARTED 
wlp2s0: CTRL-EVENT-SCAN-STARTED 
wlp4s0: CTRL-EVENT-SCAN-STARTED 
wlp0s20u5: CTRL-EVENT-SCAN-STARTED 
wlp0s20u5: CTRL-EVENT-SCAN-STARTED 
wlp0s20u5: CTRL-EVENT-SCAN-STARTED 
wlp0s20u5: CTRL-EVENT-SCAN-STARTED 
wlp0s20u5: CTRL-EVENT-SCAN-STARTED 

The corresponding output in dmesg is:

wlp0s20u5: authenticate with 00:1a:70:46:ba:b1
wlp0s20u5: send auth to 00:1a:70:46:ba:b1 (try 1/3)
wlp0s20u5: authenticated
rtl8192cu 3-5:1.0 wlp0s20u5: disabling HT/VHT due to WEP/TKIP use
wlp0s20u5: associate with 00:1a:70:46:ba:b1 (try 1/3)
wlp0s20u5: RX AssocResp from 00:1a:70:46:ba:b1 (capab=0x411 status=0 aid=1)
rtl8192cu:rtl92cu_set_hw_reg():<0-0> switch case not processed
wlp0s20u5: associated

That "switch case not processed" is harmless.

What do you see?

**Comment by Borgvall** [comment]
Sorry for the delay. But on Fedora 23 with kernel 4.2.5 the problem is disappeared.
