### ISSUE TITLE
_rtl_pci_interrupt: xxx callbacks suppressed

### ISSUE THREAD

**Issue by lavaed** [lwfinger/rtlwifi_new#505]
Messages are logged. The card is used as an access point.

4.15.0-70-generic #79-Ubuntu x86_64
RTL8812AE 802.11ac PCIe Wireless Network Adapter

**Comment by lwfinger** [comment]
That kind of message happens when the logging of messages exceeds the rate limit. As you do not provide any other messages, there is noting I else I can do.

**Comment by lavaed** [comment]
There is nothing more about the operation of the rtl8821ae driver in the logs. The rtl_pci_interrupt message appears only when traffic is downloaded to the client (TX packets of the access point). There are just a lot of these messages and they log the logs.

**Comment by lwfinger** [comment]
You should see some messages that say "IMR_TXFOVW!" in the log. The rate limiting will kick in when they come too fast.

I asked the Realtek engineer about this message. He replied
"This message is harmless. Just use a little CPU due to interrupt and some debug
message. If user doesn't like it, he can turn off IMR_TXFOVW."

"Considering TX path, a packet is coming from host and writing to DMA memory, and then
kick wifi card to do DMA. In card side, TX buffer is used to hold packets from DMA,
and a packet is freed after transmitting done or failed. If many packets are waiting
for DMA and DMA is faster than transmission in air, TX buffer will become full
frequently. When DMA is failed due to TX buffer doesn't have enough room to hold
a packet being DMAed, TXFOVW interrupt is arise."

OK, we could hold the transmits when the first overflow happens, and then restart it when the buffer is empty, but that would slow the throughput, which is probably not what you want.

As the logging seems to bother you, just comment out these 3 lines in pci.c:
        if (unlikely(intvec.intb & rtlpriv->cfg->maps[RTL_IMR_TXFOVW]) &&
            printk_ratelimit())
                RT_TRACE(rtlpriv, COMP_ERR, DBG_WARNING, "IMR_TXFOVW!\n");
I am not going to do it because I want the messages to be available for other users.

**Comment by lavaed** [comment]
Thanks. Messages are no longer in the logs.
