### ISSUE TITLE
Weak signal for Realtek 8723DE

### ISSUE THREAD

**Issue by ds-ux** [lwfinger/rtlwifi_new#509]
Hi there! I am facing Weak signal issues with RTL8723DE driver. My Wifi card shows almost full signal for my Wifi router in Windows 10, but in ubuntu, it doesn't even show that Wifi router. Whenever I use my mobile phone's Wifi Hotspot and places it next to the laptop, it shows 2 bars of signal only (42% signal strength).

I don't know what the problem is. The wifi works perfectly on Windows 10. I can share any information, if needed.

I've tried everything - Tried it in other flavors of Linux like Kali, kubuntu, fedora and Mint, Reintalled the driver module several times, but nothing worked.

What should I do ? Please HELP!

**Comment by lwfinger** [comment]
You must have discovered all the articles about ant_sel. Note that the problem is NOT with the driver, but with your laptop vendor. For whatever reason, they only installed a single antenna, but failed to program selection into the PROM. The Windows driver ignores the value in the PROM and selects the other antenna. The Linux driver follows the PROM setting and gets the wrong answer, unless you use the ant_sel option to override the PROM value.

**Comment by ds-ux** [comment]
Yeah! I found it. Thanks a lot.
