### ISSUE TITLE
Kernel 5.4.x series presents an unusable interface for RTL8188EE

### ISSUE THREAD

**Issue by vinipsmaker** [lwfinger/rtlwifi_new#517]
I'm not sure how to properly gather relevant information for the report or if this is the appropriate repository. Please let me know if I'm posting on the wrong place.

Once I've upgraded to kernel 5.4.1 (from 5.3.13), the wireless is unusable. NetworkManager still finds the wireless interface, find access points, and connects to them. But the connection goes down and up so quickly and all the time that I'm unable to use it at all. Not sure what information I should gather for a proper report.

The issue persists on 5.4.2, 5.4.6 and 5.4.10.

**Comment by lwfinger** [comment]
Did anything else in your setup change when you went from 5.3.13 to 5.4.1? If so look there because no one else has complained. If nothing in user-space changed, then you may have found a regression.
For regressions, the proper way is to find the code change between a kernel that works, and a kernel that fails.. That becomes difficult when you are using kernels outside of mainline.

I would suggest that you do the following:

git clone git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.get
cd linux
cp /boot/config-5.4.10* .config
make -jX
sudo make modules_install install

Then test the new 5.5.0-rcn kernel. In the make command above, use 2*no cpu +1 for X. For example, I have 4 cores, thus I use "make -j9". If this kernel works, then abandon all the other kernels. It if fails, then do the following:

git checkout v5.3
make -jX
sudo make modules_install install

Test this one. If it works, then do a bisection:

git checkout master
git bisect start
git bisect bad
git bisect good v5.3

Then do the "make" and "sudo make" steps and reboot that kernel. Find out if it is good or bad. Then do a "git bisect xx" where xx is good or bad depending on the result. Repeat until you determine the commit that failed. It will take 14 or 15 builds.

Note: The multiple kernels that are generated will take a lot of space in partition /. Keep an eye of the free space and delete kernels from /boot, and modules from /lib/modules to keep some space available for the make process to use.

**Comment by vinipsmaker** [comment]
Okay. Thanks. I'll try to bisect the kernel.

**Comment by ashish-yadav11** [comment]
I am also having issues with kernel 5.4 and 5.5 while connecting to my institute's wifi. I have rtl8188e as my wifi card.
In systemd journal the relevant errors are - "kernel: rtlwifi: AP off, try to reconnect now" and "NetworkManager[431]: <warn>  [1579499438.1858] sup-iface[0x55ecc3750130,wlp5s0]: connection disconnected (reason -4)". They pop up in an interval of 10 seconds or so.
Connecting to my mobile phone's hotspot works just fine.
Downgrading to kernel 5.3 solves the issue.
My cpu is very slow so I will not able to manually compile kernels.

**Comment by lwfinger** [comment]
First of all, there is no rtl8188e! There are rtl8188ee and rtl8188eu. There is a big difference. Which do you have?
Those reason 4 disconnects are due to wireless system inactivity. That is not due to a driver problem!! The driver takes the packets provided by the user-space network code, reformulates it and passes it over the air. My guess is that NetworkManager is doing something that your AP does not like, or vice versa.
As far as I remember, nothing in the rtlwifi drivers changed between 5.3 and 5.4. Of course, to verify that on your system would require a bisection, but you have already ruled that out. Just for the record, I have done many kernel bisections on a PowerBook G4. That is very slow at 4-5 hours per build, but it gets the job done. I do not build the .deb using that funny fakeroot utility. That would take at least twice as long.

**Comment by vinipsmaker** [comment]
I got some time to do the bisect. d1d1a96bdb4408d02e2bfcb32b71aba165458a80 is the first bad commit. After that, I can't use wi-fi. Anything wrong in this commit that you can find?

**Comment by lwfinger** [comment]
The fix has been submitted. See https://marc.info/?l=linux-wireless&m=158214245715595&w=2. It should be in kernel 5.6, and will then be backported to earlier kernels.
