### ISSUE TITLE
Commit d1d1a96 in rtl8188ee module causes issues when connecting to my institute's wifi

### ISSUE THREAD

**Issue by ashish-yadav11** [lwfinger/rtlwifi_new#528]
The commit d1d1a96 (at [link](https://github.com/torvalds/linux/commit/d1d1a96bdb4408d02e2bfcb32b71aba165458a80?diff=unified)) in rtl8188ee module causes problems when connecting to my institute's wifi. I am not able to connect to that wifi after this commit. The journalctl output is at [ix.io/28IX](http://ix.io/28IX) (look for "AP off, try to reconnect now").
The problem is with removal of the struct.
Adding the following back in trx.h (where it was previously) solves the issue.
`struct phy_rx_agc_info_t {`
`		#if defined(__LITTLE_ENDIAN)`
`		u8	gain:7, trsw:1;`
`	#else`
`		u8	trsw:1, gain:7;`
`	#endif`
`};`
`...`
`	struct phy_rx_agc_info_t path_agc[2];`

**Comment by lwfinger** [comment]
I am looking into this issue. If it happens with the in-tree kernel, then it should be reported at linux-wireless@vger.kernel.org.

This "solution" does not make any sense. That struct was used only once in struct phy_status_rpt to define an array path_agc - that array was never referenced. Removing it will cause a realignment of that struct, but it should not affect operation unless there is some other bug that forces a strict dependence 

Your log shows your link associating and authenticating.

Jan 20 11:23:09 hp kernel: wlp5s0: authenticate with e8:ba:70:53:e9:54
Jan 20 11:23:09 hp wpa_supplicant[448]: wlp5s0: SME: Trying to authenticate with e8:ba:70:53:e9:54 (SSID='Students' freq=2412 MHz)
supplicant interface state: scanning -> authenticating
Jan 20 11:23:09 hp kernel: wlp5s0: send auth to e8:ba:70:53:e9:54 (try 1/3)
Jan 20 11:23:09 hp kernel: wlp5s0: authenticated
Jan 20 11:23:09 hp kernel: wlp5s0: associate with e8:ba:70:53:e9:54 (try 1/3)
Jan 20 11:23:09 hp kernel: wlp5s0: RX AssocResp from e8:ba:70:53:e9:54 (capab=0x421 status=0 aid=80)
Jan 20 11:23:09 hp kernel: wlp5s0: associated
Jan 20 11:23:09 hp wpa_supplicant[448]: wlp5s0: Associated with e8:ba:70:53:e9:54

Then a little bit later, it drops the line due to inactivity.

Jan 20 11:23:21 hp kernel: rtlwifi: AP off, try to reconnect now
Jan 20 11:23:21 hp kernel: wlp5s0: Connection to AP e8:ba:70:53:e9:54 lost
Jan 20 11:23:21 hp wpa_supplicant[448]: wlp5s0: CTRL-EVENT-DISCONNECTED bssid=e8:ba:70:53:e9:54 reason=4 locally_generated=1
Jan 20 11:23:21 hp wpa_supplicant[448]: dbus: wpa_dbus_property_changed: no property SessionLength in object /fi/w1/wpa_supplicant1/Interfaces/0
Jan 20 11:23:21 hp wpa_supplicant[448]: wlp5s0: CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
Jan 20 11:23:21 hp wpa_supplicant[448]: wlp5s0: CTRL-EVENT-REGDOM-CHANGE init=USER type=COUNTRY alpha2=IN
Jan 20 11:23:21 hp NetworkManager[431]: <warn>  [1579499601.8124] sup-iface[0x55ecc3750130,wlp5s0]: connection disconnected (reason -4)

Why adding some dead code back in would prevent the drop is way beyond me. I'm working on a fix., but it will take a while.

**Comment by vinipsmaker** [comment]
Previous issue: https://github.com/lwfinger/rtlwifi_new/issues/517

I was unaware of this bisect and reached the same faulty commit. So there are at least we two who confirm this as faulty commit. I haven't verified your fix thou.

**Comment by lwfinger** [comment]
See https://marc.info/?l=linux-wireless&m=158214245715595&w=2 for the fix. It should be in kernel 5.6. Once there, it will be backported to earlier kernels. No, I do not know the time frame.

**Comment by MartorSkull** [comment]
Can confirm this patch solves the issue. Same problem (AP off trying to reconnect). After the patch this was fixed.
