### ISSUE TITLE
rtl_usb: Pending RX skbuff queue full! (qlen: 64)

### ISSUE THREAD

**Issue by ounie-os** [lwfinger/rtlwifi_new#530]
My wifi card is TP-LINK TL-WN823N 1.0 whose type is USB and my kernel version is 4.18.10 from kernel.org. Download the repositories master code and compile rtl8192c/ 、rtl8192cu/ and the core ones. Everything is ok. Load those ko files into my system and wifi is work on. 
But if the wifi trafiic is busy and the kernel will printk the message "rtl_usb: Pending RX skbuff queue full! (qlen: 64)", lots of and full of my terminal.
My board is BeagleBone Black (rev: A5A): 1GHz cpu, 512MB RAM

**Comment by lwfinger** [comment]
I increased the length of the queue to 96. That may help. The expense of the increased length is to require more memory, which is probably at a premium in your system.
The real problem is that you are receiving packets at a faster rate than your CPU can handle. The speed of memory and I/O traffic may also be a factor.
If this increase does not help, then you should probably remove the printk at lines 638-639 of file usb.c. When this condition happens, dropping the packet is the thing to do.

**Comment by ounie-os** [comment]
Do as you said that I remove the printk message and it work well for severral hours. Thank you very much.

**Comment by ounie-os** [comment]
By the way, 96 is not enough and 128 neither that i have tried. That means the rx queue will be full sooner or later if the system could not handle the packers received quickly. Just remove error printk message. If the rx queue is full, drop the packet anyway. My board is BeagleBone black with 1GHz arm and maybe it is weak for some situation.
