### ISSUE TITLE
RTL8723be has poor signal quality in recent setup

### ISSUE THREAD

**Issue by MarcelHB** [lwfinger/rtlwifi_new#55]
Since I got my Lenovo the last year, I had a perfectly working setup of some Ubuntu-based distro (14.10 initially) and a RTL8723be driven by the code of this repository.

At some point of history I did some scheduled updates, and then things started to get worse on a Kernel v3.19/Vivid. I only find a fraction of available APs, my connection to an AP in plain-sight 3 meters away is utterly bad, and working in my office, there is no chance at all to gain a stable connection any more.

I noticed you not being the happiest contributor when it comes to Ubuntu, so I just tried a mainline 4.1 RC kernel and the repo HEAD at this point. Unfortunately, nothing changes. I switched to working on some old RTL8187 based USB dongle which is working at 100% but this is only a temporary workaround.

This is what I `iwconfig`-get on my rtl8723be device on my AP:

```
wlan0     IEEE 802.11bgn  ESSID:"WLAN"  
          Mode:Managed  Frequency:2.462 GHz  Access Point: 00:00:00:00:00:00   
          Bit Rate=54 Mb/s   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr=2347 B   Fragment thr:off
          Power Management:off
          Link Quality=24/70  Signal level=-86 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:505   Missed beacon: 0
```

When I check the data on the rtl8187, everything looks the same, except `RTS thr` being set to `off`. Looking around the web, I found and tried options like:

```options rtl8723be swenc=Y fwlps=N ips=N```

or similar but nothing ever notably changed.

Please tell me if you like to see further data.

**Comment by lwfinger** [comment]
You need to do a bisection. If that is not possible, then set up Ubuntu 14.10 and try the latest code from the repo with it. That instance could be using a Live medium. You would need to install git to download the repo, but all the pieces needed to compile an out-of-kernel driver are there.  There have been very few changes in the rtl8723be code in this repo since it was created, and I cannot think of any of them that have affected signal strength. My RTL8723BE sees 7 nearby stations when scanning, and an Intel 7260 sees only 8, thus there is not a lot of difference.

**Comment by MarcelHB** [comment]
Thanks, I'll try bisecting the repo soon.

Comparing the two adapters, I have 4 APs on the 8723be, and 13 APs on 8187 -- all the ones I think I  already spotted on the native device in the past.

**Comment by lwfinger** [comment]
Interesting. My RTL8187L (Netgear WG111V2) only sees 5 APs.

**Comment by MarcelHB** [comment]
Interesting, that's exactly the device I'm using right now.

**Comment by MarcelHB** [comment]
Ok, I reverted to the initial v3.16 kernel and the driver rev of early Oct '14. Same result. Using `wavemon`, I clearly see comparatively bad signal values on the built-in rtl8723be (maybe ~50% quality of what WG111v2 gives me).

Sounds like as if this issue is more related to some broken antenna. Unless there is some UEFI-based power issue introduced - in the early days, something in there even hard-locked the wifi device - there is nothing we can do, I guess.

If so, thanks for your help anyway.

Interesting side-observation: On our Raspberry Pi (Ubuntu MATE 15.04), using an Edimax with rtl8192cu, I've had similar connectivity problems until I replaced the driver by the one from this repo two weeks ago, then anything turned smooth. I'll try it out.

**Comment by lwfinger** [comment]
Do not ever take the signal strengths of quality as absolute quantities. Most drivers have an empirical formula "to make it look nice for the customer"! The critical thing is the number of APs that can be seen. If any user-space code relies on the value of strengths, then that is a bug.

**Comment by MarcelHB** [comment]
I just tested the nano rtl9182cu device and event this one has a slightly better AP visibility. So I guess I suffer from hardware connectivity problems and the driver is fine.

**Comment by braykov** [comment]
I am facing the same problem + many others: I can rarely connect; when I connect it often disconnects; modprobe -r and modprobe don't usually work; sometimes I need to restart to get a connection and it still happens on a rare occasion.
Yesterday I tried the 'rock' branch and it suddenly connected and with a very fast and stable connections. Today, however I cannot connect again.
I don't know what to try anymore.
Is there a guide with debug steps I can perform to gather information that could help you investigate?

I am with Ubuntu 15.04, kernel 3.19.0-25, updated with the latest repository (changes 2-3 days ago).
I have also tried kernels 4.1 (+RC). No luck.

Sometimes after modprobe the system just freezes and needs a hard reset.

**Comment by geromek** [comment]
What worked for me was enabling the MSI parameter [message signal interupt ]. I have a lenovo Z50 laptop. My wifi would work with all wifi laptop manufacturers but i was having a problem with a Lancorm wifi router at a Hotel I once stayed.

what i did was this. I scrowled to the file "sw.c" in the folder

"/home/peter/rtlwifi_new/rtl8723be"

Then in the sw.c file, I initiated the variable "msi_support" to "false" under the data type "rtl_mod_params rtl8723be_mod_params" i.e

static struct rtl_mod_params rtl8723be_mod_params = {
.sw_crypto = false,
.inactiveps = true,
.swctrl_lps = false,
.fwctrl_lps = true,
.msi_support = false,
};

Since msi_support is by default disabled, we have to appropriately initialize it as disabled,

I then complied the code, ie

cd rtl8723be
make clean
sudo make install
sudo modprobe rtl8723be

after that I set the msi parameter to 1, in the file "rtl8723be.conf" which can be found under
"/etc/modprobe.d"
i.e
options rtl8723be fwlps=N ips=N swenc=Y msi=1

You may have to reboot the computer and wait after a couple of minutes after restarting the browser for the msi to be triggered.

This worked for a lenovo z50. Depending on your pc, you may toggle and choose instead an msi of 0

**Comment by lwfinger** [comment]
By now I'm sure that you know about the "modinfo" command and that it lists all the module parameters, and their default values. I have no idea why one connecting to a particular AP could be affected by the interrupt method, but I do know that Lenovo boxes sometimes have strange interfacing.

An msi of zero is the default. Nothing needs to be done.

**Comment by MarcelHB** [comment]
Ok, `rock.new_btcoex`-Branch and `ant_sel` not set to `1` as (as discussed #28) did the trick. That's some hell of AP firework here now, never seen that on other devices here.

Thanks, I'll close it. :smiley:
