### ISSUE TITLE
rtlwifi_new extended branch not compiling with 5.4.36 kernel

### ISSUE THREAD

**Issue by gotti79** [lwfinger/rtlwifi_new#554]
There was a change in the 5.4.36 kernel which breaks compiling.

It is not really complicated to fix sorry for not using the way over pull request which would be probably more correct but the git tree is a internal one.

Here is the Fix to get it compile again, so if any other one fall into this issue...

diff --git a/rc.c b/rc.c
index 62e6645..8bdb5a5 100644
--- a/rc.c
+++ b/rc.c
@@ -294,7 +294,11 @@ static void rtl_rate_update(void *ppriv,
 }
 #endif
 
+#if (LINUX_VERSION_CODE >= KERNEL_VERSION(5, 4, 36))
+static void *rtl_rate_alloc(struct ieee80211_hw *hw)
+#else
 static void *rtl_rate_alloc(struct ieee80211_hw *hw, struct dentry *debugfsdir)
+#endif
 {
        struct rtl_priv *rtlpriv = rtl_priv(hw);
        return rtlpriv;

Best regards,

Stefan Gottwald

**Comment by hwpfeil** [comment]
Thank you, Mr. Gottwald! I appreciate the diff. Just ran into this issue on a remote laptop. If I had booted 5.4.36, I would have had to physically revert back to 5.4.35.

**Comment by JuliusFreudenberger** [comment]
> Found a different issue on line 336
> 
> rtlwifi/rc.c:336:11: error: initialization of ‘void * (*)(struct ieee80211_hw _)’ from incompatible pointer type ‘void * (_)(struct ieee80211_hw *, struct dentry *)’ [-Werror=incompatible-pointer-types]
> 336 | .alloc = rtl_rate_alloc,
> | ^~~~~~~~~~~~~~
> rtlwifi/rc.c:336:11: note: (near initialization for ‘rtl_rate_ops.alloc’)

I can confirm this error (for me it is line 340 but the rest is the same) on kernel 5.6.8 and 5.4.36 (on arch: linux and linux-lts)

**Comment by lwfinger** [comment]
Blame that on your distro. They have backported a change made in kernel 5.7.0-rc3 to 5.4.36. I consider this to be reprehensible behavior. It used to be only Ubuntu that did it, but now more distros have this nasty behavior!

I cannot follow the changes made by every distro. The conditional compilation statements would be very long, and it would take all my time just to keep up. Due to the distros bad behavior, you will need to patch this yourself. Where I have a test for 5.7.0, you will need to change it to 5.4.36. I recommend that you do it with a patch file, not a git commit, as the latter will get you into difficulty when you next do a git pull.

**Comment by hwpfeil** [comment]
Clean download of 5.4.36 from kernel.org. This is not a "distro" issue. Rtlwifi compiles and installs 5.4.35. Only change was 5.4.36 -- make bzImage; make modules; make modules_install <reboot> cd /usr/src/rtlwifi; make. I don't know how to fix an incompatible pointer type as I am not familiar with the rtlwifi code.
Suggest ripping out all of the kernel-specific ifdefs and support only the most recent kernel.org releases. Let "distros" fix their own.

**Comment by lwfinger** [comment]
That is what I do, except that I handle all standard kernels. You will see a test for kernel 5.7.0 near the offending line. I always use mainline kernels, and the sources build here!

As your distro stupidly backports kernel APIs, you will have to adjust the #if statements, and keep adjusting them, as well as handle the git conflicts, etc. Otherwise, build a mainline kernels.

By the way, this is the 4th time I have written essentially the same stuff today, and it is only 12:30 here.

**Comment by lwfinger** [comment]
Sorry, I did not read your post correctly. You need to post the error if you want me to fix it. Obviously, someone backported a change.

**Comment by hwpfeil** [comment]
I figured out your error in rc.c:

<       .alloc = rtl_rate_alloc,
---
>       .alloc = (const void*) rtl_rate_alloc,

**Comment by lwfinger** [comment]
I figured out the problem, and I retract most of the nasty things I said about distros.

It is fixed now. The problem was actually caused by a friend of mine, that I will chew out privately.

**Comment by gotti79** [comment]
Sorry for the obvious to short report we use the default mainline 5.4.36 as I denied using the ubuntu kernel anymore a long time ago due to various issues. Yes we modify the kernel too but not in this areas, next time I will try to be more clear about this, as I also searched the commit which caused the issue I probably should have add this here.
