### ISSUE TITLE
Issue with rc.c with Linux 5.6.8

### ISSUE THREAD

**Issue by burdi01** [lwfinger/rtlwifi_new#556]
rtlwifi_new-extended, Latest commit Apr 29 2113764.
It looks like the commit for (the closed) issue "Issue with rc.c with Linux 5.7-rc3 #549" now causes (or suffers from) the same error with linux 5.6.8 ...

.....
  CC [M]  /usr/src/rtlwifi_new-extended/phydm/halrf/halrf.o
  CC [M]  /usr/src/rtlwifi_new-extended/pci.o
/usr/src/rtlwifi_new-extended/rc.c:340:11: error: initialization of ‘void * (*)(struct ieee80211_hw *)’ from incompatible pointer type ‘void * (*)(struct ieee80211_hw *, struct dentry *)’ [-Werror=incompatible-pointer-types]
  340 |  .alloc = rtl_rate_alloc,
      |           ^~~~~~~~~~~~~~
/usr/src/rtlwifi_new-extended/rc.c:340:11: note: (near initialization for ‘rtl_rate_ops.alloc’)
  CC [M]  /usr/src/rtlwifi_new-extended/rtl8821ae/rf.o
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:268: /usr/src/rtlwifi_new-extended/rc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
  CC [M]  /usr/src/rtlwifi_new-extended/rtl8821ae/sw.o
.....

**Comment by burdi01** [comment]
Changing the kernel version test resolves the build error:

--- rc.c.orig	2020-04-29 19:56:47.000000000 +0200
+++ rc.c	2020-04-30 14:37:24.000000000 +0200
@@ -294,7 +294,7 @@
 }
 #endif
 
-#if (LINUX_VERSION_CODE >= KERNEL_VERSION(5, 7, 0))
+#if (LINUX_VERSION_CODE >= KERNEL_VERSION(5, 6, 8))
 static void *rtl_rate_alloc(struct ieee80211_hw *hw)
 #else
 static void *rtl_rate_alloc(struct ieee80211_hw *hw, struct dentry *debugfsdir)

**Comment by lwfinger** [comment]
The API did not change in vanilla, mainline kernels until 5.7.0-rc3. Your problem is caused by your distro backporting kernel APIs. To handle this case I would need to test the kernel version, the Ubuntu version, the Fedora version, the openSUSE version, ... That would be nearly impossible, and a lot more work than I am willing to devote, thus you have to fix it yourself the way you did.

Keep in mind that future pulls will get a conflict that you will need to fix manually, and then reapply your change again if you are using a kernel older than 5.7.

**Comment by burdi01** [comment]
Ok, I will wait and see.
Kind regards, Dick
:D
