### ISSUE TITLE
Mesh support on rtl8192c

### ISSUE THREAD

**Issue by richiejp** [lwfinger/rtlwifi_new#59]
Hello,

I have been experimenting with MESH mode on kernel 4.0.7 and although it appears to be sending beacons out, it doesn't seem able to establish a connection.

I have two rtl8192c based dongles connected to identical VMs and am using the following commands to set up the mesh:
```
iw dev wls160u2 set type mesh
ip addr add 192.168.2.1 dev wls160u2
ip link set wls160u2 up
iw dev wls160u2 mesh join lmmesh
```
Running `iw dev wls160u2 mpath dump` produces no results and there is nothing regarding mesh in dmesg. I can't find any other information on this other than the git commit which fixed sending beacons in mesh mode, so I am guessing there is still something which needs to be implemented?

**Comment by lwfinger** [comment]
When you post for these devices, please state that you have RTL8192CU, or that your devices use driver rtl8192cu. The only way that I know that you have the USB variant, rather than the RTL8192CE for PCIe, is the name that your kernel gave it. If you still had the old-style name (wlanX), I would not have known.

Driver rtl8102cu is a real mess, and is included in this repo for completeness. I am not sure that the version here even matches what is in the kernel, as tracking those changes has very low priority. I got the original version of the driver from Realtek, cleaned up style issues, and it was added to the kernel in 2.6.39. Since then, Realtek has made no updates, and I know nothing of the internals of the chip. I do fix issues that generate an oops, but there is not much more I can do.

I suggest that you write Taehee Yoo who submitted the beacon patch with a Cc to linux-wireless@vger.kernel.org. You can get his address from the patch. He is very familiar with the beaconing issues, and might be able to help.

**Comment by richiejp** [comment]
Ok, sorry about that, I was being lazy, I will refer to the mailing list. Thanks.
