### ISSUE TITLE
Make the makefile(installation method) safer

### ISSUE THREAD

**Issue by cata0309** [lwfinger/rtlwifi_new#602]
From what I managed to understand from the make file it won't work safely, for sure.
The install rule is dangerous because it's removing the existing modules from the kernel and the overwriting them.The kernel has this file:
`/lib/modules/5.6.13-153.current/kernel/drivers/net/wireless/realtek/rtw88/rtw88.ko`
which is overwritten by the install rule.
I hope something good is to be done about this `sudo make install` can brick a system in a hurry if you don't know what it's doing.
My request is to find a way to avoid conflicting files !

**Comment by lwfinger** [comment]
OK, you provide the updates and I will look at them.

My system has had both kinds ofr files, AND I have never bricked it.

**Comment by yagoplx** [comment]
Since this git repo provides the same drivers that are in the kernel... it would make sense to replace the files on install (else modprobe wouldn't know where your new driver is). I don't see how building some random wifi module then placing it where the kernel's default would be could brick a system.

**Comment by lwfinger** [comment]
It could not "brick" a system; however, having conflicting drivers could cause a crash on boot. That is the reason the install process deletes some default drivers.
