### ISSUE TITLE
RTL8723DE not working with this new rtw88

### ISSUE THREAD

**Issue by VenomIND** [lwfinger/rtlwifi_new#632]
**_Issue :_** My chip RTL8723DE was working earlier with https://github.com/lwfinger/rtlwifi_new ,but now with rtw88 no wifi option is showing tested with debian,manjaro,Ubuntu

Simulation :  sudo apt-get update
sudo apt-get install make gcc linux-headers-$(uname -r) build-essential git

git clone https://github.com/lwfinger/rtlwifi_new.git -b rtw88
cd rtlwifi_new
make
sudo make install

sudo modprobe -r rtw_8723de
sudo modprobe rtw_8723de ant_sel=2

**_Earlier Solution :_**  sudo apt install git build-essential dkms linux-headers-$(uname -r)
git clone -b extended --single-branch https://github.com/lwfinger/rtlwifi_new.git
cd rtlwifi_new
sudo dkms add ../rtlwifi_new
sudo dkms install rtlwifi-new/0.6
sudo modprobe -v rtl8723de ant_sel=2

Low signal fix
sudo /bin/sh -c 'echo "options rtl8723de ant_sel=4" >> /etc/modprobe.d/rtl8723de.conf'

This is how my life was spending ..Now rtw88 cant even load.. Please Help and provide those files back or somthing .. and I have also reported a bug at **https://bugzilla.kernel.org/**  and **You replied there** that this module will be added in **Linux kernel 5.8** .. But what about Debian users now ?

Thank you for understanding . an early reply is highly appriciated .

**Comment by Lollixzc** [comment]
Could you provide the output of `lsmod | grep rt` ?

**Comment by lwfinger** [comment]
Of course not. Anyone that was running ant_sel=4 is completely clueless.

I will NEVER return those files because I had to answer 10 to 20 of these E-mails each day. I have no idea why Debian, Ubuntu, and all their derivatives fail with rtw88, but I have no inclination to debug it for them. For me, openSUSE works just fine.

**Comment by lwfinger** [comment]
I relented and installed Ubuntu 20.04. Guess what? It worked "out-of-the-box" with driver rtw88. Obviously, someone at Ubuntu has merged the trial code into their kernel.

Just for kicks, I installed the pre-requisites listed in README.md, cloned the rtw88 branch of this repo, did a 'sudo modprobe -rv rtwpci, and did a 'make' and 'sudo make install'. Then I did 'sudo modprobe -v rtw_8723de', and it just worked. It also worked after a reboot.

At this point, 'lsmod | grep rtw' shows rtw_8723de, rtw_8723d, rtw_pci, and rtw_core.

What ever problems you are having, it is because you are not following the instructions!

**Comment by VenomIND** [comment]
@lwfinger Sir, I compleatly understand your point about ant_sel=4 .. **I tried as instructed ant_sel=2 & again 3** but both of them had slow signals with rtlwifi_new but the 4 was working great ... maybe that only on my system... and Yaa Ubuntu 20.04 supports than out of the box...

 But I dont like what Ubuntu is doing so im not using that . I have using **debian 10 and manjaro** .. and sorry to say but its not working & I cant find the dnks options also.

again I havnt tried SUSE .. and could you please confirm me that as you saaid earlier that this module will be added into **Kernel 5.8** .. Is it there and works out of the box ?

Thanks for your time and effort :-)

**Comment by yagoplx** [comment]
If ant_sel=4 is working so well for you, that means you don't need ant_sel. The driver will just ignore any value that isn't 1 or 2. Any other value does absolutely nothing, so all you have with you is placebo.

That parameter is only needed for some crappy RTL8623DE devices with a missing antenna, really. These seem to happen a lot in HP laptops.

-------- Mensagem Original --------
Ativo 5 de jul de 2020 23:54, VenomIND escreveu:

**Comment by yagoplx** [comment]
Overall this repository is a mess, with the master branch empty, and hundreds of open issues referring to now defunct code. If @lwfinger is so tired of dumb issues, he should at least clean up this repository, including the insane layout.

The documentation needs to be clear with what these drivers are for, because people come here thinking that they don't have "real drivers" and that they will leave this place with everything fixed and working nice.

-------- Mensagem Original --------
Ativo 5 de jul de 2020 23:54, VenomIND escreveu:

**Comment by Lollixzc** [comment]
I perfectly agree with @yagoplx about all the mess of the repository. Many people come from old articles that refers to this repository, and don't understand/or read the documentation. It could be refactored in a new repository, much cleaner and without all these issues, because many of them aren't related to the new rtw88 branch.

**Comment by VenomIND** [comment]
@yagoplx @Lollixzc Yup true HP is using one of the worse chipsets RTL8723DE currently only Ubuntu 20.04 supports it out of the box but  sir @lwfinger said It will be added in **Kernel 5.8** so ..

**Comment by lwfinger** [comment]
I NEVER said it would be in kernel 5.8! What I said is that it might be in 5.8, but that is now impossible as it ran into some problems with the reviewers.
