### ISSUE TITLE
Release Date

### ISSUE THREAD

**Issue by tarek-salah** [lwfinger/rtlwifi_new#79]
When will this driver be added to the official Linux Kernel?

**Comment by lwfinger** [comment]
Never. All the the rtlwifi family are already in the kernel!

**Comment by tarek-salah** [comment]
but when there's an update for Linux kernel , I always need to reinstall the driver using 
```
sudo make install 
```

My current Linux kernel is 3.13.0-73
My Wireless Network Adapter : Realtek Semiconductor Co., Ltd. RTL8723BE PCIe

**Comment by lwfinger** [comment]
Of course you need to reinstall whenever your kernel changes. Once a kernel is released, only the simplest of changes are backported to it, and then only to those kernels with long-term support. Kernel 3.13 is not one of them.

You and people in your situation are the reason this repo exists. Once you upgrade your distro to something newer, you may not have to reinstall every time the kernel changes. In the meantime, I will continue to backport changes here and include the necessary modifications so that the changes will compile on kernels as old as yours.

**Comment by tarek-salah** [comment]
Thanks for response
