### ISSUE TITLE
RTL8723be doesnt work on Ubuntu 14.04 64 bit, it works correctly in 32 bit

### ISSUE THREAD

**Issue by AnakTeka** [lwfinger/rtlwifi_new#87]
Hi, I'm using a HP Pavilion with RTL8723be chipset on Ubuntu 14.04 64 bit kernel 3.13.0-24-generic, I have compiled a module from https://github.com/lwfinger/rtlwifi_new with test brach and I loaded the module succesfully. 

But it doesn't show any WiFi networks unless I load the module with msi=1 ips=0, with those parameters I could see the WiFi networks but I was unable to connect to any network even the network without WPA2. 

The thing that bothered me most is this exact steps work correctly on Ubuntu 14.04 32bit version. I could connect to any WiFi networks that shown.

What kind information do you need for the analysis? I'm kind of new to Linux.

Thanks in advace.
This is my first time asking on github page I hope I'm asking this question on the right place.
And English is not my mother language please bear with me.

**Comment by lwfinger** [comment]
The need to use "msi=1" between 32- and 64-bit systems is due to the way that your box handles interrupts. Obviously, standard interrupt triggering is OK for 32-bit, but the support routines require MSI in the 64-bit case. To keep the driver from ever crashing, the default must be "msi=0".

Using "ips=0" has no effect on the ability to find networks in a scan or to connect with them. With some APs, that option may be necessary to maintain a stable connection, but that step occurs much later in the connection history.

Usually, problems in connecting to networks that can be seen in a scan are the result of low signal strength. Is it possible for you to download the Ubuntu 15.10 Desktop iso files in both 32- and 64-bit versions, burn them to CD or a USB stick, and boot the live version? If so, please run the following command in each version and post the results:

sudo iw dev <wldev> scan | egrep "signal|SSID"

Replace the <wldev> part with the device shown in the command "iw dev | grep Interface".

On the 64-bit system, you may need to do the following:

sudo modprobe -rv rtl8723be
sudo modprobe -v rtl8723be msi=1

**Comment by coyoteRidgeCodeClubAdmin** [comment]
Good morning. I have that same HW (HP 15ac-163nr with RTL8723be), I'm hoping we can help each other here, if not I can start my own thread.

- Clean install of 14.04
- ran all updates
- followed rtl8723be update found [here](http://askubuntu.com/questions/629679/rtl8723ae-unstable-on-ubuntu-14-04)
- iwlist scan shows Signal Level=-74 dBm

However, when I try to connect, syslog shows "association took to long"

Thank you for all you do, please let me know if I'm missing something obvious, or if I can provide more information.

**Comment by coyoteRidgeCodeClubAdmin** [comment]
update: If I sit directly under my access point, then it works (Ubiquiti Networks UAP‑AC‑LR).

I'm guessing the radio is in the wrong power mode or HP builds a crappy antenna (possibly both).
Off to find a data sheet for the rtl8723be to see if I can help. Please let me know if you have one.
This card has a special HP part number, I wonder if there is secret sauce so the HP BIOS white-list can identify it?

**Comment by lwfinger** [comment]
Networks with a signal level of -74 dBm will show up in a scan, but they are way too low to associate.

On a number of newer laptops, the manufacturers are only including a single antenna; however, the contents of the EEPROM that tell which antenna connector to use do not match the one that they actually use. This problem has just been known for a few weeks. Realtek will be modifying the driver to work no matter which antenna is selected, but that will take a while.

The only fix at the moment is to open the machine and plug the single antenna lead onto the other connector. Most people find it on #1 and have to move it to #2.

There are no data sheets available for any of the Realtek PCI devices. Even though I work closely with them, I have no access to any documentation other than what is contained in the drivers.

The special sauce is in the HP BIOS itself, which is programmed to recognize only certain PCI IDs.

**Comment by coyoteRidgeCodeClubAdmin** [comment]
That worked!
Moving the antenna to channel 2 results in -28 dBm.

I currently have
```
options rtl8723be fwlps=0 swlps=0 ips=0 msi=1
```

Are these options too much?

Thank you for the insight and the quick response!
Please let me know if I can help with the OP problem with similar HW.

**Comment by lwfinger** [comment]
Using "ips=0" make swlps and fwlps be irrelevant, but they won't hurt.

**Comment by lwfinger** [comment]
For anyone else reading this thread:
Realtek just informed me that the routine to select the connected antenna automatically has been delayed, but they supplied a corrected routine to fix the "ant_sel" module parameter.

To access this new code, use the "rock.new_btcoex" branch and load the module with the "ant_sel=Y" option, where Y is 1 or 2.
